///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace D4H_BP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the D4H_BPRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("49b1f21a-85f7-4646-8be0-81bb0e2f51e9")]
    public partial class D4H_BPRepository : RepoGenBaseFolder
    {
        static D4H_BPRepository instance = new D4H_BPRepository();
        D4H_BPRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        D4H_BPRepositoryFolders.LoginToYourAccountLogOnAppFolder _logintoyouraccountlogon;

        /// <summary>
        /// Gets the singleton class instance representing the D4H_BPRepository element repository.
        /// </summary>
        [RepositoryFolder("49b1f21a-85f7-4646-8be0-81bb0e2f51e9")]
        public static D4H_BPRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public D4H_BPRepository() 
            : base("D4H_BPRepository", "/", null, 0, false, "49b1f21a-85f7-4646-8be0-81bb0e2f51e9", ".\\RepositoryImages\\D4H_BPRepository49b1f21a.rximgres")
        {
            _applicationundertest = new D4H_BPRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _logintoyouraccountlogon = new D4H_BPRepositoryFolders.LoginToYourAccountLogOnAppFolder(this);
        }

#region Variables

        string _domainname = "dole-dev-simplemdg-web.cfapps.ap11.hana.ondemand.com";

        /// <summary>
        /// Gets or sets the value of variable domainname.
        /// </summary>
        [TestVariable("a17ded76-ebae-484c-b62c-6174d0eef3d4")]
        public string domainname
        {
            get { return _domainname; }
            set { _domainname = value; }
        }

        string _vaOjType = "ZB00_CU_GD1";

        /// <summary>
        /// Gets or sets the value of variable vaOjType.
        /// </summary>
        [TestVariable("7bb44758-0e06-4e54-a2b0-3565dd1e2c96")]
        public string vaOjType
        {
            get { return _vaOjType; }
            set { _vaOjType = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("49b1f21a-85f7-4646-8be0-81bb0e2f51e9")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("73a9cfb6-88e2-4d87-9ccf-276fc3630317")]
        public virtual D4H_BPRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The LoginToYourAccountLogOn folder.
        /// </summary>
        [RepositoryFolder("b0a24bd6-756d-4068-a148-1e7c7f7ce207")]
        public virtual D4H_BPRepositoryFolders.LoginToYourAccountLogOnAppFolder LoginToYourAccountLogOn
        {
            get { return _logintoyouraccountlogon; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class D4H_BPRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("73a9cfb6-88e2-4d87-9ccf-276fc3630317")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            D4H_BPRepositoryFolders.InputHeaderFolder _inputheader;
            D4H_BPRepositoryFolders.TabRolesFolder _tabroles;
            D4H_BPRepositoryFolders.TabGeneralDataFolder _tabgeneraldata;
            D4H_BPRepositoryFolders.TabAddressFolder _tabaddress;
            RepoItemInfo _btn_mainappInfo;
            RepoItemInfo _icon_requestorInfo;
            RepoItemInfo _lb_logoutInfo;
            RepoItemInfo _btn_logoutconfirmInfo;
            RepoItemInfo _lb_loginInfo;
            RepoItemInfo _lb_mytaskInfo;
            RepoItemInfo _lb_businessrequestsInfo;
            RepoItemInfo _btn_submitrequestInfo;
            RepoItemInfo _txt_selectotInfo;
            RepoItemInfo _btn_nextInfo;
            RepoItemInfo _btn_choosetemplateInfo;
            RepoItemInfo _txt_selectsearchInfo;
            RepoItemInfo _btn_searchactionInfo;
            RepoItemInfo _lb_choosetemplateInfo;
            RepoItemInfo _btn_submitotInfo;
            RepoItemInfo _txt_note4submitInfo;
            RepoItemInfo _btn_submitInfo;
            RepoItemInfo _lb_requestwithcrInfo;
            RepoItemInfo _btn_okrequestsuccessInfo;
            RepoItemInfo _txt_changerequestfilterInfo;
            RepoItemInfo _btn_okfilterInfo;
            RepoItemInfo _btn_optionInfo;
            RepoItemInfo _lb_cancelrequestInfo;
            RepoItemInfo _btn_confirmcancelInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain=$domainname]", parentFolder, 30000, null, false, "73a9cfb6-88e2-4d87-9ccf-276fc3630317", "")
            {
                _inputheader = new D4H_BPRepositoryFolders.InputHeaderFolder(this);
                _tabroles = new D4H_BPRepositoryFolders.TabRolesFolder(this);
                _tabgeneraldata = new D4H_BPRepositoryFolders.TabGeneralDataFolder(this);
                _tabaddress = new D4H_BPRepositoryFolders.TabAddressFolder(this);
                _btn_mainappInfo = new RepoItemInfo(this, "Btn_MainApp", ".//span[#'mainApp']/a[@innertext='Main App']", "", 30000, null, "c09d2421-c263-4e9a-9c69-b91ba1b184b8");
                _icon_requestorInfo = new RepoItemInfo(this, "Icon_Requestor", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/?/?/header//span[@role='button']", "", 30000, null, "b854d91b-8b42-46ff-9a0b-0f619aa38abe");
                _lb_logoutInfo = new RepoItemInfo(this, "lb_Logout", ".//div[#'sap-ui-static']/div/div/div/?/?/ul/li[2]//span[@innertext='Logout']", ".//div[#'sap-ui-static']//span[@innertext='Logout']", 30000, null, "eecc1416-2863-4909-b13a-a72ffce9f47a");
                _btn_logoutconfirmInfo = new RepoItemInfo(this, "Btn_logoutConfirm", ".//div[#'sap-ui-static']/?/?/footer/div/button[1]/span", "", 30000, null, "c606f687-a2bc-4698-971c-4d35a41eef0e");
                _lb_loginInfo = new RepoItemInfo(this, "lb_Login", ".//div[#'login_back']/?/?/a[@innertext='Login']", "", 30000, null, "166bae03-fdc1-4881-a73d-d132bea6ceb1");
                _lb_mytaskInfo = new RepoItemInfo(this, "lb_Mytask", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/?/?/header/div/div/div[2]/div[1]/div[3]/div[1]/?/?/span[@innertext='My Tasks ⁝']", ".//body[#'simplemdg']//span[@innertext='My Tasks ⁝']", 30000, null, "e854b3fa-a010-4d35-84f4-d1c56c309306");
                _lb_businessrequestsInfo = new RepoItemInfo(this, "lb_BusinessRequests", ".//div[#'sap-ui-static']/div[3]/div/div/div/div/div/div[2]//span[@innertext='Business Requests']", ".//div[#'sap-ui-static']//span[@innertext='Business Requests']", 30000, null, "116968cf-c116-44d4-b1f1-98d3112f75ea");
                _btn_submitrequestInfo = new RepoItemInfo(this, "Btn_SubmitRequest", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/*/?/?/section/div/div/div/div[1]/div[2]/div[4]/button[@title>'Submit a new Master Data']/span[1]/span[2]", ".//body[#'simplemdg']//button[@title>'Submit a new Master Data']/span[1]/span[2]", 30000, null, "2e687814-a957-4274-b59b-d6734f578b0f");
                _txt_selectotInfo = new RepoItemInfo(this, "txt_SelectOT", ".//div[#'sap-ui-static']/div[4]/div/div/div/div[1]//input[@type='text']", ".//div[#'sap-ui-static']//input[@type='text']", 30000, null, "12ab2647-acbb-4f52-a995-66cacfa648dc");
                _btn_nextInfo = new RepoItemInfo(this, "Btn_Next", ".//div[#'sap-ui-static']/div[4]/div//button/span/span[2]", ".//div[#'sap-ui-static']//button/span/span[2]", 30000, null, "ef8bab22-50e9-4200-b3f6-2d8229ce1a58");
                _btn_choosetemplateInfo = new RepoItemInfo(this, "Btn_ChooseTemplate", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div[2]/div/header/div[1]/div/div/div[1]/div/div/div/div[3]/button[@title='Select method']/span[1]/span[2]", "", 30000, null, "9527dea6-0e82-448a-9354-4fbe61c67d76");
                _txt_selectsearchInfo = new RepoItemInfo(this, "txt_SelectSearch", ".//div[#'sap-ui-static']/div[6]/header[2]//form/input[@type='search']", "", 30000, null, "cfceda89-39ed-4471-8dce-e5bae1b9b31c");
                _btn_searchactionInfo = new RepoItemInfo(this, "Btn_SearchAction", ".//div[#'sap-ui-static']/div[6]/header[2]//?/div[@title='Search']", ".//div[#'sap-ui-static']//div[@title='Search']", 30000, null, "0b5ce56a-46c8-456a-8f3c-2dcbf2fc4736");
                _lb_choosetemplateInfo = new RepoItemInfo(this, "lb_ChooseTemplate", ".//div[#'sap-ui-static']/div[6]/section//table/tbody/tr[1]/td[2]//span[@innertext=$vaOjType]", "", 30000, null, "b3b881e5-d729-475a-9652-e5b0c015fa97");
                _btn_submitotInfo = new RepoItemInfo(this, "Btn_SubmitOT", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div/div/header/div[1]/div/div/div[3]/div/button[4]/span/span[2]/tag[@innertext='Submit']", ".//body[#'simplemdg']//tag[@innertext='Submit']", 30000, null, "97ccde7d-968b-4b37-a33b-0df027bae400");
                _txt_note4submitInfo = new RepoItemInfo(this, "txt_Note4Submit", ".//div[@class='sapMDialogScrollCont']/?/?/div/textarea[@required='False']", ".//div[#'__dialog2-scrollCont']//textarea[@required='False']", 30000, null, "d4ae641f-c1ba-4e17-99dc-9ce863faa29b");
                _btn_submitInfo = new RepoItemInfo(this, "Btn_Submit", ".//div[#'sap-ui-static']/div/footer/div/button[1]//tag[@innertext='Submit']", ".//div[#'sap-ui-static']//tag[@innertext='Submit']", 30000, null, "45698048-e5f5-49cc-acb1-dcc990cd6c4b");
                _lb_requestwithcrInfo = new RepoItemInfo(this, "lb_RequestwithCR", ".//div[@safeclass='sapMDialogScrollCont']/span[@safeclass='sapMMsgBoxText sapMText sapMTextMaxWidth sapUiSelectable' and @tagname='span']", "", 30000, null, "4bf5881d-23d2-4d99-a995-cde725c4d077");
                _btn_okrequestsuccessInfo = new RepoItemInfo(this, "Btn_OKRequestSuccess", ".//div[#'sap-ui-static']/div/footer/div/button[1]//tag[@innertext='Ok']", ".//div[#'sap-ui-static']//tag[@innertext='Ok']", 30000, null, "f0d51055-7c39-414e-a002-05a51ed548db");
                _txt_changerequestfilterInfo = new RepoItemInfo(this, "txt_ChangeRequestFilter", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div[3]/?/?/section/?/?/aside/div[2]/div[2]/?/?/form[@action='https://dole-dev-simplemdg-web.cfapps.ap11.hana.ondemand.com/main/index.html#/requestHistory']/input[@type='search']", ".//body[#'simplemdg']//input[@type='search']", 30000, null, "7edaaafc-90ff-4e99-b4b3-97899f961741");
                _btn_okfilterInfo = new RepoItemInfo(this, "Btn_OKFilter", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div[3]/?/?/section/?/?/aside/div[2]/div[15]/div[2]/button//tag[@innertext='Go']", ".//body[#'simplemdg']//tag[@innertext='Go']", 30000, null, "555f455a-7035-4d18-9c5c-13e4a8b9e605");
                _btn_optionInfo = new RepoItemInfo(this, "Btn_Option", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div/?/?/section/div/div/div/div[3]/?/?/table/tbody/tr[1]/td/?/?/button/span", ".//body[#'simplemdg']//tbody/tr[1]/td[10]/div/button/span", 30000, null, "4f76fc06-65e3-4060-92fa-170273384e7e");
                _lb_cancelrequestInfo = new RepoItemInfo(this, "lb_CancelRequest", ".//div[#'sap-ui-static']//li[@title='Cancel this request']/div[@innertext='Cancel this request' and @safeclass='sapUiMnuItmTxt']", "", 30000, null, "9ac94f22-8c9e-4e9b-b715-8b40f71f9caa");
                _btn_confirmcancelInfo = new RepoItemInfo(this, "Btn_ConfirmCancel", ".//div[#'sap-ui-static']/div/footer/div/button[1]//tag[@innertext='Yes']", ".//div[#'sap-ui-static']//tag[@innertext='Yes']", 30000, null, "78f9e097-8062-4dfd-a555-5536adcfb241");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("73a9cfb6-88e2-4d87-9ccf-276fc3630317")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("73a9cfb6-88e2-4d87-9ccf-276fc3630317")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Btn_MainApp item.
            /// </summary>
            [RepositoryItem("c09d2421-c263-4e9a-9c69-b91ba1b184b8")]
            public virtual Ranorex.ATag Btn_MainApp
            {
                get
                {
                    return _btn_mainappInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Btn_MainApp item info.
            /// </summary>
            [RepositoryItemInfo("c09d2421-c263-4e9a-9c69-b91ba1b184b8")]
            public virtual RepoItemInfo Btn_MainAppInfo
            {
                get
                {
                    return _btn_mainappInfo;
                }
            }

            /// <summary>
            /// The Icon_Requestor item.
            /// </summary>
            [RepositoryItem("b854d91b-8b42-46ff-9a0b-0f619aa38abe")]
            public virtual Ranorex.SpanTag Icon_Requestor
            {
                get
                {
                    return _icon_requestorInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Icon_Requestor item info.
            /// </summary>
            [RepositoryItemInfo("b854d91b-8b42-46ff-9a0b-0f619aa38abe")]
            public virtual RepoItemInfo Icon_RequestorInfo
            {
                get
                {
                    return _icon_requestorInfo;
                }
            }

            /// <summary>
            /// The lb_Logout item.
            /// </summary>
            [RepositoryItem("eecc1416-2863-4909-b13a-a72ffce9f47a")]
            public virtual Ranorex.SpanTag lb_Logout
            {
                get
                {
                    return _lb_logoutInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The lb_Logout item info.
            /// </summary>
            [RepositoryItemInfo("eecc1416-2863-4909-b13a-a72ffce9f47a")]
            public virtual RepoItemInfo lb_LogoutInfo
            {
                get
                {
                    return _lb_logoutInfo;
                }
            }

            /// <summary>
            /// The Btn_logoutConfirm item.
            /// </summary>
            [RepositoryItem("c606f687-a2bc-4698-971c-4d35a41eef0e")]
            public virtual Ranorex.SpanTag Btn_logoutConfirm
            {
                get
                {
                    return _btn_logoutconfirmInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Btn_logoutConfirm item info.
            /// </summary>
            [RepositoryItemInfo("c606f687-a2bc-4698-971c-4d35a41eef0e")]
            public virtual RepoItemInfo Btn_logoutConfirmInfo
            {
                get
                {
                    return _btn_logoutconfirmInfo;
                }
            }

            /// <summary>
            /// The lb_Login item.
            /// </summary>
            [RepositoryItem("166bae03-fdc1-4881-a73d-d132bea6ceb1")]
            public virtual Ranorex.ATag lb_Login
            {
                get
                {
                    return _lb_loginInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The lb_Login item info.
            /// </summary>
            [RepositoryItemInfo("166bae03-fdc1-4881-a73d-d132bea6ceb1")]
            public virtual RepoItemInfo lb_LoginInfo
            {
                get
                {
                    return _lb_loginInfo;
                }
            }

            /// <summary>
            /// The lb_Mytask item.
            /// </summary>
            [RepositoryItem("e854b3fa-a010-4d35-84f4-d1c56c309306")]
            public virtual Ranorex.SpanTag lb_Mytask
            {
                get
                {
                    return _lb_mytaskInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The lb_Mytask item info.
            /// </summary>
            [RepositoryItemInfo("e854b3fa-a010-4d35-84f4-d1c56c309306")]
            public virtual RepoItemInfo lb_MytaskInfo
            {
                get
                {
                    return _lb_mytaskInfo;
                }
            }

            /// <summary>
            /// The lb_BusinessRequests item.
            /// </summary>
            [RepositoryItem("116968cf-c116-44d4-b1f1-98d3112f75ea")]
            public virtual Ranorex.SpanTag lb_BusinessRequests
            {
                get
                {
                    return _lb_businessrequestsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The lb_BusinessRequests item info.
            /// </summary>
            [RepositoryItemInfo("116968cf-c116-44d4-b1f1-98d3112f75ea")]
            public virtual RepoItemInfo lb_BusinessRequestsInfo
            {
                get
                {
                    return _lb_businessrequestsInfo;
                }
            }

            /// <summary>
            /// The Btn_SubmitRequest item.
            /// </summary>
            [RepositoryItem("2e687814-a957-4274-b59b-d6734f578b0f")]
            public virtual Ranorex.SpanTag Btn_SubmitRequest
            {
                get
                {
                    return _btn_submitrequestInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Btn_SubmitRequest item info.
            /// </summary>
            [RepositoryItemInfo("2e687814-a957-4274-b59b-d6734f578b0f")]
            public virtual RepoItemInfo Btn_SubmitRequestInfo
            {
                get
                {
                    return _btn_submitrequestInfo;
                }
            }

            /// <summary>
            /// The txt_SelectOT item.
            /// </summary>
            [RepositoryItem("12ab2647-acbb-4f52-a995-66cacfa648dc")]
            public virtual Ranorex.InputTag txt_SelectOT
            {
                get
                {
                    return _txt_selectotInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_SelectOT item info.
            /// </summary>
            [RepositoryItemInfo("12ab2647-acbb-4f52-a995-66cacfa648dc")]
            public virtual RepoItemInfo txt_SelectOTInfo
            {
                get
                {
                    return _txt_selectotInfo;
                }
            }

            /// <summary>
            /// The Btn_Next item.
            /// </summary>
            [RepositoryItem("ef8bab22-50e9-4200-b3f6-2d8229ce1a58")]
            public virtual Ranorex.SpanTag Btn_Next
            {
                get
                {
                    return _btn_nextInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Btn_Next item info.
            /// </summary>
            [RepositoryItemInfo("ef8bab22-50e9-4200-b3f6-2d8229ce1a58")]
            public virtual RepoItemInfo Btn_NextInfo
            {
                get
                {
                    return _btn_nextInfo;
                }
            }

            /// <summary>
            /// The Btn_ChooseTemplate item.
            /// </summary>
            [RepositoryItem("9527dea6-0e82-448a-9354-4fbe61c67d76")]
            public virtual Ranorex.SpanTag Btn_ChooseTemplate
            {
                get
                {
                    return _btn_choosetemplateInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Btn_ChooseTemplate item info.
            /// </summary>
            [RepositoryItemInfo("9527dea6-0e82-448a-9354-4fbe61c67d76")]
            public virtual RepoItemInfo Btn_ChooseTemplateInfo
            {
                get
                {
                    return _btn_choosetemplateInfo;
                }
            }

            /// <summary>
            /// The txt_SelectSearch item.
            /// </summary>
            [RepositoryItem("cfceda89-39ed-4471-8dce-e5bae1b9b31c")]
            public virtual Ranorex.InputTag txt_SelectSearch
            {
                get
                {
                    return _txt_selectsearchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_SelectSearch item info.
            /// </summary>
            [RepositoryItemInfo("cfceda89-39ed-4471-8dce-e5bae1b9b31c")]
            public virtual RepoItemInfo txt_SelectSearchInfo
            {
                get
                {
                    return _txt_selectsearchInfo;
                }
            }

            /// <summary>
            /// The Btn_SearchAction item.
            /// </summary>
            [RepositoryItem("0b5ce56a-46c8-456a-8f3c-2dcbf2fc4736")]
            public virtual Ranorex.DivTag Btn_SearchAction
            {
                get
                {
                    return _btn_searchactionInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Btn_SearchAction item info.
            /// </summary>
            [RepositoryItemInfo("0b5ce56a-46c8-456a-8f3c-2dcbf2fc4736")]
            public virtual RepoItemInfo Btn_SearchActionInfo
            {
                get
                {
                    return _btn_searchactionInfo;
                }
            }

            /// <summary>
            /// The lb_ChooseTemplate item.
            /// </summary>
            [RepositoryItem("b3b881e5-d729-475a-9652-e5b0c015fa97")]
            public virtual Ranorex.SpanTag lb_ChooseTemplate
            {
                get
                {
                    return _lb_choosetemplateInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The lb_ChooseTemplate item info.
            /// </summary>
            [RepositoryItemInfo("b3b881e5-d729-475a-9652-e5b0c015fa97")]
            public virtual RepoItemInfo lb_ChooseTemplateInfo
            {
                get
                {
                    return _lb_choosetemplateInfo;
                }
            }

            /// <summary>
            /// The Btn_SubmitOT item.
            /// </summary>
            [RepositoryItem("97ccde7d-968b-4b37-a33b-0df027bae400")]
            public virtual Ranorex.WebElement Btn_SubmitOT
            {
                get
                {
                    return _btn_submitotInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Btn_SubmitOT item info.
            /// </summary>
            [RepositoryItemInfo("97ccde7d-968b-4b37-a33b-0df027bae400")]
            public virtual RepoItemInfo Btn_SubmitOTInfo
            {
                get
                {
                    return _btn_submitotInfo;
                }
            }

            /// <summary>
            /// The txt_Note4Submit item.
            /// </summary>
            [RepositoryItem("d4ae641f-c1ba-4e17-99dc-9ce863faa29b")]
            public virtual Ranorex.TextAreaTag txt_Note4Submit
            {
                get
                {
                    return _txt_note4submitInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The txt_Note4Submit item info.
            /// </summary>
            [RepositoryItemInfo("d4ae641f-c1ba-4e17-99dc-9ce863faa29b")]
            public virtual RepoItemInfo txt_Note4SubmitInfo
            {
                get
                {
                    return _txt_note4submitInfo;
                }
            }

            /// <summary>
            /// The Btn_Submit item.
            /// </summary>
            [RepositoryItem("45698048-e5f5-49cc-acb1-dcc990cd6c4b")]
            public virtual Ranorex.WebElement Btn_Submit
            {
                get
                {
                    return _btn_submitInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Btn_Submit item info.
            /// </summary>
            [RepositoryItemInfo("45698048-e5f5-49cc-acb1-dcc990cd6c4b")]
            public virtual RepoItemInfo Btn_SubmitInfo
            {
                get
                {
                    return _btn_submitInfo;
                }
            }

            /// <summary>
            /// The lb_RequestwithCR item.
            /// </summary>
            [RepositoryItem("4bf5881d-23d2-4d99-a995-cde725c4d077")]
            public virtual Ranorex.SpanTag lb_RequestwithCR
            {
                get
                {
                    return _lb_requestwithcrInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The lb_RequestwithCR item info.
            /// </summary>
            [RepositoryItemInfo("4bf5881d-23d2-4d99-a995-cde725c4d077")]
            public virtual RepoItemInfo lb_RequestwithCRInfo
            {
                get
                {
                    return _lb_requestwithcrInfo;
                }
            }

            /// <summary>
            /// The Btn_OKRequestSuccess item.
            /// </summary>
            [RepositoryItem("f0d51055-7c39-414e-a002-05a51ed548db")]
            public virtual Ranorex.WebElement Btn_OKRequestSuccess
            {
                get
                {
                    return _btn_okrequestsuccessInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Btn_OKRequestSuccess item info.
            /// </summary>
            [RepositoryItemInfo("f0d51055-7c39-414e-a002-05a51ed548db")]
            public virtual RepoItemInfo Btn_OKRequestSuccessInfo
            {
                get
                {
                    return _btn_okrequestsuccessInfo;
                }
            }

            /// <summary>
            /// The txt_ChangeRequestFilter item.
            /// </summary>
            [RepositoryItem("7edaaafc-90ff-4e99-b4b3-97899f961741")]
            public virtual Ranorex.InputTag txt_ChangeRequestFilter
            {
                get
                {
                    return _txt_changerequestfilterInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_ChangeRequestFilter item info.
            /// </summary>
            [RepositoryItemInfo("7edaaafc-90ff-4e99-b4b3-97899f961741")]
            public virtual RepoItemInfo txt_ChangeRequestFilterInfo
            {
                get
                {
                    return _txt_changerequestfilterInfo;
                }
            }

            /// <summary>
            /// The Btn_OKFilter item.
            /// </summary>
            [RepositoryItem("555f455a-7035-4d18-9c5c-13e4a8b9e605")]
            public virtual Ranorex.WebElement Btn_OKFilter
            {
                get
                {
                    return _btn_okfilterInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Btn_OKFilter item info.
            /// </summary>
            [RepositoryItemInfo("555f455a-7035-4d18-9c5c-13e4a8b9e605")]
            public virtual RepoItemInfo Btn_OKFilterInfo
            {
                get
                {
                    return _btn_okfilterInfo;
                }
            }

            /// <summary>
            /// The Btn_Option item.
            /// </summary>
            [RepositoryItem("4f76fc06-65e3-4060-92fa-170273384e7e")]
            public virtual Ranorex.SpanTag Btn_Option
            {
                get
                {
                    return _btn_optionInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Btn_Option item info.
            /// </summary>
            [RepositoryItemInfo("4f76fc06-65e3-4060-92fa-170273384e7e")]
            public virtual RepoItemInfo Btn_OptionInfo
            {
                get
                {
                    return _btn_optionInfo;
                }
            }

            /// <summary>
            /// The lb_CancelRequest item.
            /// </summary>
            [RepositoryItem("9ac94f22-8c9e-4e9b-b715-8b40f71f9caa")]
            public virtual Ranorex.DivTag lb_CancelRequest
            {
                get
                {
                    return _lb_cancelrequestInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The lb_CancelRequest item info.
            /// </summary>
            [RepositoryItemInfo("9ac94f22-8c9e-4e9b-b715-8b40f71f9caa")]
            public virtual RepoItemInfo lb_CancelRequestInfo
            {
                get
                {
                    return _lb_cancelrequestInfo;
                }
            }

            /// <summary>
            /// The Btn_ConfirmCancel item.
            /// </summary>
            [RepositoryItem("78f9e097-8062-4dfd-a555-5536adcfb241")]
            public virtual Ranorex.WebElement Btn_ConfirmCancel
            {
                get
                {
                    return _btn_confirmcancelInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Btn_ConfirmCancel item info.
            /// </summary>
            [RepositoryItemInfo("78f9e097-8062-4dfd-a555-5536adcfb241")]
            public virtual RepoItemInfo Btn_ConfirmCancelInfo
            {
                get
                {
                    return _btn_confirmcancelInfo;
                }
            }

            /// <summary>
            /// The InputHeader folder.
            /// </summary>
            [RepositoryFolder("8853041f-407e-4fc5-a916-cbe43979aba0")]
            public virtual D4H_BPRepositoryFolders.InputHeaderFolder InputHeader
            {
                get { return _inputheader; }
            }

            /// <summary>
            /// The TabRoles folder.
            /// </summary>
            [RepositoryFolder("ab5e10e2-7497-4c8d-889e-f3b5c09c3dc1")]
            public virtual D4H_BPRepositoryFolders.TabRolesFolder TabRoles
            {
                get { return _tabroles; }
            }

            /// <summary>
            /// The TabGeneralData folder.
            /// </summary>
            [RepositoryFolder("ace8c805-913c-4668-b243-0fa764ee042e")]
            public virtual D4H_BPRepositoryFolders.TabGeneralDataFolder TabGeneralData
            {
                get { return _tabgeneraldata; }
            }

            /// <summary>
            /// The TabAddress folder.
            /// </summary>
            [RepositoryFolder("1ef3afbc-8ca4-4d32-9c26-e9321a3fcbde")]
            public virtual D4H_BPRepositoryFolders.TabAddressFolder TabAddress
            {
                get { return _tabaddress; }
            }
        }

        /// <summary>
        /// The InputHeaderFolder folder.
        /// </summary>
        [RepositoryFolder("8853041f-407e-4fc5-a916-cbe43979aba0")]
        public partial class InputHeaderFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txt_requestdescriptionInfo;
            RepoItemInfo _txt_priorityInfo;
            RepoItemInfo _txt_reasonInfo;
            RepoItemInfo _txt_otherreasonInfo;

            /// <summary>
            /// Creates a new InputHeader  folder.
            /// </summary>
            public InputHeaderFolder(RepoGenBaseFolder parentFolder) :
                    base("InputHeader", "", parentFolder, 0, null, false, "8853041f-407e-4fc5-a916-cbe43979aba0", "")
            {
                _txt_requestdescriptionInfo = new RepoItemInfo(this, "txt_RequestDescription", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div[2]/div/header/header/section/div/div/div[1]/div[@title='Request Description']/div/textarea[@placeholder='Request Description']", ".//body[#'simplemdg']//textarea[@placeholder='Request Description']", 30000, null, "0e1cf07d-756e-488b-b8b2-fe6d9b951267");
                _txt_priorityInfo = new RepoItemInfo(this, "txt_Priority", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div//header/header/section/div/div/div[2]/div[@title='Priority']/?/?/input[@type='text']", ".//body[#'simplemdg']//div[@title='Priority']/div/input[@type='text']", 30000, null, "f5f72da4-5c74-4867-9a54-c32ab1743a1a");
                _txt_reasonInfo = new RepoItemInfo(this, "txt_Reason", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div//header/header/section/div/div/div[3]/div[@title='Reason']/?/?/input[@type='text']", ".//body[#'simplemdg']//div[@title='Reason']/div/input[@type='text']", 30000, null, "20e0bea2-8628-4e7c-a277-c1b50ad17f65");
                _txt_otherreasonInfo = new RepoItemInfo(this, "txt_OtherReason", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div[2]/div/header/header/section/div/div/div[4]/div[@title='Reason']/div/textarea[@placeholder='Other reason']", ".//body[#'simplemdg']//textarea[@placeholder='Other reason']", 30000, null, "c10d78df-b5a5-478c-b4be-5a6f7eb1748d");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8853041f-407e-4fc5-a916-cbe43979aba0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txt_RequestDescription item.
            /// </summary>
            [RepositoryItem("0e1cf07d-756e-488b-b8b2-fe6d9b951267")]
            public virtual Ranorex.TextAreaTag txt_RequestDescription
            {
                get
                {
                    return _txt_requestdescriptionInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The txt_RequestDescription item info.
            /// </summary>
            [RepositoryItemInfo("0e1cf07d-756e-488b-b8b2-fe6d9b951267")]
            public virtual RepoItemInfo txt_RequestDescriptionInfo
            {
                get
                {
                    return _txt_requestdescriptionInfo;
                }
            }

            /// <summary>
            /// The txt_Priority item.
            /// </summary>
            [RepositoryItem("f5f72da4-5c74-4867-9a54-c32ab1743a1a")]
            public virtual Ranorex.InputTag txt_Priority
            {
                get
                {
                    return _txt_priorityInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_Priority item info.
            /// </summary>
            [RepositoryItemInfo("f5f72da4-5c74-4867-9a54-c32ab1743a1a")]
            public virtual RepoItemInfo txt_PriorityInfo
            {
                get
                {
                    return _txt_priorityInfo;
                }
            }

            /// <summary>
            /// The txt_Reason item.
            /// </summary>
            [RepositoryItem("20e0bea2-8628-4e7c-a277-c1b50ad17f65")]
            public virtual Ranorex.InputTag txt_Reason
            {
                get
                {
                    return _txt_reasonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_Reason item info.
            /// </summary>
            [RepositoryItemInfo("20e0bea2-8628-4e7c-a277-c1b50ad17f65")]
            public virtual RepoItemInfo txt_ReasonInfo
            {
                get
                {
                    return _txt_reasonInfo;
                }
            }

            /// <summary>
            /// The txt_OtherReason item.
            /// </summary>
            [RepositoryItem("c10d78df-b5a5-478c-b4be-5a6f7eb1748d")]
            public virtual Ranorex.TextAreaTag txt_OtherReason
            {
                get
                {
                    return _txt_otherreasonInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The txt_OtherReason item info.
            /// </summary>
            [RepositoryItemInfo("c10d78df-b5a5-478c-b4be-5a6f7eb1748d")]
            public virtual RepoItemInfo txt_OtherReasonInfo
            {
                get
                {
                    return _txt_otherreasonInfo;
                }
            }
        }

        /// <summary>
        /// The TabRolesFolder folder.
        /// </summary>
        [RepositoryFolder("ab5e10e2-7497-4c8d-889e-f3b5c09c3dc1")]
        public partial class TabRolesFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selectrolesInfo;
            RepoItemInfo _checkboxrolesInfo;

            /// <summary>
            /// Creates a new TabRoles  folder.
            /// </summary>
            public TabRolesFolder(RepoGenBaseFolder parentFolder) :
                    base("TabRoles", "", parentFolder, 0, null, false, "ab5e10e2-7497-4c8d-889e-f3b5c09c3dc1", "")
            {
                _selectrolesInfo = new RepoItemInfo(this, "SelectRoles", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div[2]/div/header/div[2]/div/div[2]/div/button[1]//tag[@innertext='Roles']", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div[2]/div/header/div[2]/div/div[2]/div/button[1]/span/span/tag", 30000, null, "f1e2c9a5-ed3a-4675-b765-b5866ae14900");
                _checkboxrolesInfo = new RepoItemInfo(this, "CheckboxRoles", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div[2]/div/div[2]/div/section[2]/section[1]/div[2]/div/div[1]//table/thead/tr/th[2]/?/?/div", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div[2]/div/div[2]/div/section[2]/section[1]/div[2]/div/div[1]/div/div/div/table/thead/tr/th[2]/div/div", 30000, null, "cd2cd1a1-4488-4211-8380-0a0d8c0605d3");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ab5e10e2-7497-4c8d-889e-f3b5c09c3dc1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SelectRoles item.
            /// </summary>
            [RepositoryItem("f1e2c9a5-ed3a-4675-b765-b5866ae14900")]
            public virtual Ranorex.WebElement SelectRoles
            {
                get
                {
                    return _selectrolesInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The SelectRoles item info.
            /// </summary>
            [RepositoryItemInfo("f1e2c9a5-ed3a-4675-b765-b5866ae14900")]
            public virtual RepoItemInfo SelectRolesInfo
            {
                get
                {
                    return _selectrolesInfo;
                }
            }

            /// <summary>
            /// The CheckboxRoles item.
            /// </summary>
            [RepositoryItem("cd2cd1a1-4488-4211-8380-0a0d8c0605d3")]
            public virtual Ranorex.DivTag CheckboxRoles
            {
                get
                {
                    return _checkboxrolesInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CheckboxRoles item info.
            /// </summary>
            [RepositoryItemInfo("cd2cd1a1-4488-4211-8380-0a0d8c0605d3")]
            public virtual RepoItemInfo CheckboxRolesInfo
            {
                get
                {
                    return _checkboxrolesInfo;
                }
            }
        }

        /// <summary>
        /// The TabGeneralDataFolder folder.
        /// </summary>
        [RepositoryFolder("ace8c805-913c-4668-b243-0fa764ee042e")]
        public partial class TabGeneralDataFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lb_generaldataInfo;
            RepoItemInfo _txt_businesspartnerInfo;
            RepoItemInfo _txt_categoryInfo;
            RepoItemInfo _txt_titleInfo;
            RepoItemInfo _txt_name1Info;

            /// <summary>
            /// Creates a new TabGeneralData  folder.
            /// </summary>
            public TabGeneralDataFolder(RepoGenBaseFolder parentFolder) :
                    base("TabGeneralData", "", parentFolder, 0, null, false, "ace8c805-913c-4668-b243-0fa764ee042e", "")
            {
                _lb_generaldataInfo = new RepoItemInfo(this, "lb_GeneralData", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div/div/header/div[2]/div/div[2]/div/button[2]//tag[@innertext='General Data']", ".//body[#'simplemdg']//section/div/div/div/div/div/div/div[4]/div/header/div[2]/div/div[2]/div/button[2]/span/span/tag", 30000, null, "a5c8df62-0fd0-4490-a4cb-d35fbcb5da18");
                _txt_businesspartnerInfo = new RepoItemInfo(this, "txt_BusinessPartner", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div[2]/div/div[2]/div/section[2]/section[2]/div[2]/div/div[1]/div/div/div/div/section/div/div[1]/div[2]//input[@type='text']", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div[2]/div/div[2]/div/section[2]/section[2]/div[2]/div/div[1]/div/div/div/div/section/div/div[1]/div[2]/div/div/input[@type='text']", 30000, null, "ff201921-84c2-44f0-9ce0-969e2de24645");
                _txt_categoryInfo = new RepoItemInfo(this, "txt_Category", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div[2]/div/div[2]/div/section[2]/section[2]/div[2]/div/div[1]/div/div//section/div/div[4]/div[2]//input[@type='text']", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div[2]/div/div[2]/div/section[2]/section[2]/div[2]/div/div[1]/div/div/div/div/section/div/div[4]/div[2]/div/div/input[@type='text']", 30000, null, "c7e3a7e2-e866-49ab-a976-a47fa11f44de");
                _txt_titleInfo = new RepoItemInfo(this, "txt_Title", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div[2]/div/div[2]/div/section[2]/section[2]/div[2]/div/div[1]/div/div//section/div/div[5]/div[2]//input[@type='text']", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div[2]/div/div[2]/div/section[2]/section[2]/div[2]/div/div[1]/div/div/div/div/section/div/div[5]/div[2]/div/div/input[@type='text']", 30000, null, "97089a28-528d-49cf-a15a-33e60c0fb242");
                _txt_name1Info = new RepoItemInfo(this, "txt_Name1", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div[2]/div/div[2]/div/section[2]/section[2]/div[2]/div/div[1]/div/div//section/div/div[6]/div[2]//input[@type='text']", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div[2]/div/div[2]/div/section[2]/section[2]/div[2]/div/div[1]/div/div/div/div/section/div/div[6]/div[2]/div/div/input[@type='text']", 30000, null, "d742a002-5834-48f7-adc3-ac99750d492b");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ace8c805-913c-4668-b243-0fa764ee042e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The lb_GeneralData item.
            /// </summary>
            [RepositoryItem("a5c8df62-0fd0-4490-a4cb-d35fbcb5da18")]
            public virtual Ranorex.WebElement lb_GeneralData
            {
                get
                {
                    return _lb_generaldataInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The lb_GeneralData item info.
            /// </summary>
            [RepositoryItemInfo("a5c8df62-0fd0-4490-a4cb-d35fbcb5da18")]
            public virtual RepoItemInfo lb_GeneralDataInfo
            {
                get
                {
                    return _lb_generaldataInfo;
                }
            }

            /// <summary>
            /// The txt_BusinessPartner item.
            /// </summary>
            [RepositoryItem("ff201921-84c2-44f0-9ce0-969e2de24645")]
            public virtual Ranorex.InputTag txt_BusinessPartner
            {
                get
                {
                    return _txt_businesspartnerInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_BusinessPartner item info.
            /// </summary>
            [RepositoryItemInfo("ff201921-84c2-44f0-9ce0-969e2de24645")]
            public virtual RepoItemInfo txt_BusinessPartnerInfo
            {
                get
                {
                    return _txt_businesspartnerInfo;
                }
            }

            /// <summary>
            /// The txt_Category item.
            /// </summary>
            [RepositoryItem("c7e3a7e2-e866-49ab-a976-a47fa11f44de")]
            public virtual Ranorex.InputTag txt_Category
            {
                get
                {
                    return _txt_categoryInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_Category item info.
            /// </summary>
            [RepositoryItemInfo("c7e3a7e2-e866-49ab-a976-a47fa11f44de")]
            public virtual RepoItemInfo txt_CategoryInfo
            {
                get
                {
                    return _txt_categoryInfo;
                }
            }

            /// <summary>
            /// The txt_Title item.
            /// </summary>
            [RepositoryItem("97089a28-528d-49cf-a15a-33e60c0fb242")]
            public virtual Ranorex.InputTag txt_Title
            {
                get
                {
                    return _txt_titleInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_Title item info.
            /// </summary>
            [RepositoryItemInfo("97089a28-528d-49cf-a15a-33e60c0fb242")]
            public virtual RepoItemInfo txt_TitleInfo
            {
                get
                {
                    return _txt_titleInfo;
                }
            }

            /// <summary>
            /// The txt_Name1 item.
            /// </summary>
            [RepositoryItem("d742a002-5834-48f7-adc3-ac99750d492b")]
            public virtual Ranorex.InputTag txt_Name1
            {
                get
                {
                    return _txt_name1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_Name1 item info.
            /// </summary>
            [RepositoryItemInfo("d742a002-5834-48f7-adc3-ac99750d492b")]
            public virtual RepoItemInfo txt_Name1Info
            {
                get
                {
                    return _txt_name1Info;
                }
            }
        }

        /// <summary>
        /// The TabAddressFolder folder.
        /// </summary>
        [RepositoryFolder("1ef3afbc-8ca4-4d32-9c26-e9321a3fcbde")]
        public partial class TabAddressFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tab_addressInfo;
            RepoItemInfo _txt_districtInfo;
            RepoItemInfo _txt_postalcodeInfo;
            RepoItemInfo _txt_cityInfo;
            RepoItemInfo _btn_selectcountryInfo;
            RepoItemInfo _lb_selectcountryInfo;
            RepoItemInfo _btn_addemailiconInfo;
            RepoItemInfo _txt_emailInfo;
            RepoItemInfo _btn_addemailInfo;
            RepoItemInfo _txt_searchcountryInfo;
            RepoItemInfo _btn_searchcountryInfo;

            /// <summary>
            /// Creates a new TabAddress  folder.
            /// </summary>
            public TabAddressFolder(RepoGenBaseFolder parentFolder) :
                    base("TabAddress", "", parentFolder, 0, null, false, "1ef3afbc-8ca4-4d32-9c26-e9321a3fcbde", "")
            {
                _tab_addressInfo = new RepoItemInfo(this, "Tab_Address", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div/div/header/div[2]/div/div[2]/div/button[3]//tag[@innertext='Address']", ".//body[#'simplemdg']//section/div/div/div/div/div/div/div[4]/div/header/div[2]/div/div[2]/div/button[3]/span/span/tag", 30000, null, "e77b721a-3c4d-4d2b-9067-973c59eb2fcf");
                _txt_districtInfo = new RepoItemInfo(this, "txt_District", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div/div/div[2]/div/section[2]/section[3]/div[2]/div/div[1]/div/div[1]//section/div/div[9]/div[2]//input[@type='text']", ".//body[#'simplemdg']//section/div/div/div/div/div/div/div[4]/div/div[2]/div/section[2]/section[3]/div[2]/div/div[1]/div/div[1]/div/div/div/section/div/div[9]/div[2]/div/div/input[@type='text']", 30000, null, "4974aab4-f19e-4844-a05a-be87c7a3906b");
                _txt_postalcodeInfo = new RepoItemInfo(this, "txt_PostalCode", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div/div/div[2]/div/section[2]/section[3]/div[2]/div/div[1]/div/div[1]//section/div/div[10]/div[2]//input[@type='text']", ".//body[#'simplemdg']//section/div/div/div/div/div/div/div[4]/div/div[2]/div/section[2]/section[3]/div[2]/div/div[1]/div/div[1]/div/div/div/section/div/div[10]/div[2]/div/div/input[@type='text']", 30000, null, "9de8a011-fb06-4120-af65-bc651f1db239");
                _txt_cityInfo = new RepoItemInfo(this, "txt_City", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div/div/div[2]/div/section[2]/section[3]/div[2]/div/div[1]/div/div[1]//section/div/div[10]/div[3]//input[@type='text']", ".//body[#'simplemdg']//section/div/div/div/div/div/div/div[4]/div/div[2]/div/section[2]/section[3]/div[2]/div/div[1]/div/div[1]/div/div/div/section/div/div[10]/div[3]/div/div/input[@type='text']", 30000, null, "8efe3ccb-5588-405b-b53a-84cfd68520e2");
                _btn_selectcountryInfo = new RepoItemInfo(this, "Btn_SelectCountry", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div/div/div[2]/div/section[2]/section[3]/div[2]/div/div[1]/div/div[1]//section/div/div[11]/div[2]/div/div/div[2]/span[2]", ".//body[#'simplemdg']//section/div/div/div/div/div/div/div[4]/div/div[2]/div/section[2]/section[3]/div[2]/div/div[1]/div/div[1]/div/div/div/section/div/div[11]/div[2]/div/div/div[2]/span[2]", 30000, null, "d0755f29-c656-41f5-91ed-a6a67efded73");
                _lb_selectcountryInfo = new RepoItemInfo(this, "lb_SelectCountry", ".//div[@class='sapMDialogScrollCont sapMDialogStretchContent']/?/?/table/tbody/tr/td[3]/span[@innertext='USA']", "", 30000, null, "00ef16c2-8129-4ff1-b854-fc1e39c1a3ff");
                _btn_addemailiconInfo = new RepoItemInfo(this, "Btn_AddEmailIcon", ".//body[#'simplemdg']/div[3]/div/div/div/div/div/div[2]/section/div/div/div/div/div/div/div/div/div[2]/div/section[2]/section[3]/div[2]/div/div[1]/div/div[3]/div/div/div[6]/div/div[1]/button[@title='Add']/span[1]/span", "", 30000, null, "fa650443-7207-42c1-825a-b141a67e7ffd");
                _txt_emailInfo = new RepoItemInfo(this, "txt_Email", ".//div[@class='sapMDialogScrollCont']/div/div/section/div/div/div[2]//input[@type='text']", ".//div[#'__dialog0-scrollCont']//input[@type='text']", 30000, null, "82ac2cb6-08e4-48a6-9cfb-10f7dfc686bd");
                _btn_addemailInfo = new RepoItemInfo(this, "Btn_AddEmail", ".//div[#'sap-ui-static']/div/footer/div/button[1]//tag[@innertext='Add']", ".//div[#'sap-ui-static']//tag[@innertext='Add']", 30000, null, "f1e09b41-ca90-4b1f-8636-8fa2b9fed998");
                _txt_searchcountryInfo = new RepoItemInfo(this, "txt_SearchCountry", ".//div[@safeclass='sapMBarChild sapMSF']/?/?/input[@type='search']", ".//div[#'__dialog3-searchField']/?/?/input[@type='search']", 30000, null, "d08fba14-b904-4baf-8682-ae07c710e544");
                _btn_searchcountryInfo = new RepoItemInfo(this, "Btn_SearchCountry", ".//div[@class='sapMSFS sapMSFB']", ".//div[#'__dialog0-searchField-search']", 30000, null, "e6ddcc47-2018-4cdf-9578-08151bc67a0a");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1ef3afbc-8ca4-4d32-9c26-e9321a3fcbde")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab_Address item.
            /// </summary>
            [RepositoryItem("e77b721a-3c4d-4d2b-9067-973c59eb2fcf")]
            public virtual Ranorex.WebElement Tab_Address
            {
                get
                {
                    return _tab_addressInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Tab_Address item info.
            /// </summary>
            [RepositoryItemInfo("e77b721a-3c4d-4d2b-9067-973c59eb2fcf")]
            public virtual RepoItemInfo Tab_AddressInfo
            {
                get
                {
                    return _tab_addressInfo;
                }
            }

            /// <summary>
            /// The txt_District item.
            /// </summary>
            [RepositoryItem("4974aab4-f19e-4844-a05a-be87c7a3906b")]
            public virtual Ranorex.InputTag txt_District
            {
                get
                {
                    return _txt_districtInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_District item info.
            /// </summary>
            [RepositoryItemInfo("4974aab4-f19e-4844-a05a-be87c7a3906b")]
            public virtual RepoItemInfo txt_DistrictInfo
            {
                get
                {
                    return _txt_districtInfo;
                }
            }

            /// <summary>
            /// The txt_PostalCode item.
            /// </summary>
            [RepositoryItem("9de8a011-fb06-4120-af65-bc651f1db239")]
            public virtual Ranorex.InputTag txt_PostalCode
            {
                get
                {
                    return _txt_postalcodeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_PostalCode item info.
            /// </summary>
            [RepositoryItemInfo("9de8a011-fb06-4120-af65-bc651f1db239")]
            public virtual RepoItemInfo txt_PostalCodeInfo
            {
                get
                {
                    return _txt_postalcodeInfo;
                }
            }

            /// <summary>
            /// The txt_City item.
            /// </summary>
            [RepositoryItem("8efe3ccb-5588-405b-b53a-84cfd68520e2")]
            public virtual Ranorex.InputTag txt_City
            {
                get
                {
                    return _txt_cityInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_City item info.
            /// </summary>
            [RepositoryItemInfo("8efe3ccb-5588-405b-b53a-84cfd68520e2")]
            public virtual RepoItemInfo txt_CityInfo
            {
                get
                {
                    return _txt_cityInfo;
                }
            }

            /// <summary>
            /// The Btn_SelectCountry item.
            /// </summary>
            [RepositoryItem("d0755f29-c656-41f5-91ed-a6a67efded73")]
            public virtual Ranorex.SpanTag Btn_SelectCountry
            {
                get
                {
                    return _btn_selectcountryInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Btn_SelectCountry item info.
            /// </summary>
            [RepositoryItemInfo("d0755f29-c656-41f5-91ed-a6a67efded73")]
            public virtual RepoItemInfo Btn_SelectCountryInfo
            {
                get
                {
                    return _btn_selectcountryInfo;
                }
            }

            /// <summary>
            /// The lb_SelectCountry item.
            /// </summary>
            [RepositoryItem("00ef16c2-8129-4ff1-b854-fc1e39c1a3ff")]
            public virtual Ranorex.SpanTag lb_SelectCountry
            {
                get
                {
                    return _lb_selectcountryInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The lb_SelectCountry item info.
            /// </summary>
            [RepositoryItemInfo("00ef16c2-8129-4ff1-b854-fc1e39c1a3ff")]
            public virtual RepoItemInfo lb_SelectCountryInfo
            {
                get
                {
                    return _lb_selectcountryInfo;
                }
            }

            /// <summary>
            /// The Btn_AddEmailIcon item.
            /// </summary>
            [RepositoryItem("fa650443-7207-42c1-825a-b141a67e7ffd")]
            public virtual Ranorex.SpanTag Btn_AddEmailIcon
            {
                get
                {
                    return _btn_addemailiconInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Btn_AddEmailIcon item info.
            /// </summary>
            [RepositoryItemInfo("fa650443-7207-42c1-825a-b141a67e7ffd")]
            public virtual RepoItemInfo Btn_AddEmailIconInfo
            {
                get
                {
                    return _btn_addemailiconInfo;
                }
            }

            /// <summary>
            /// The txt_Email item.
            /// </summary>
            [RepositoryItem("82ac2cb6-08e4-48a6-9cfb-10f7dfc686bd")]
            public virtual Ranorex.InputTag txt_Email
            {
                get
                {
                    return _txt_emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_Email item info.
            /// </summary>
            [RepositoryItemInfo("82ac2cb6-08e4-48a6-9cfb-10f7dfc686bd")]
            public virtual RepoItemInfo txt_EmailInfo
            {
                get
                {
                    return _txt_emailInfo;
                }
            }

            /// <summary>
            /// The Btn_AddEmail item.
            /// </summary>
            [RepositoryItem("f1e09b41-ca90-4b1f-8636-8fa2b9fed998")]
            public virtual Ranorex.WebElement Btn_AddEmail
            {
                get
                {
                    return _btn_addemailInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The Btn_AddEmail item info.
            /// </summary>
            [RepositoryItemInfo("f1e09b41-ca90-4b1f-8636-8fa2b9fed998")]
            public virtual RepoItemInfo Btn_AddEmailInfo
            {
                get
                {
                    return _btn_addemailInfo;
                }
            }

            /// <summary>
            /// The txt_SearchCountry item.
            /// </summary>
            [RepositoryItem("d08fba14-b904-4baf-8682-ae07c710e544")]
            public virtual Ranorex.InputTag txt_SearchCountry
            {
                get
                {
                    return _txt_searchcountryInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_SearchCountry item info.
            /// </summary>
            [RepositoryItemInfo("d08fba14-b904-4baf-8682-ae07c710e544")]
            public virtual RepoItemInfo txt_SearchCountryInfo
            {
                get
                {
                    return _txt_searchcountryInfo;
                }
            }

            /// <summary>
            /// The Btn_SearchCountry item.
            /// </summary>
            [RepositoryItem("e6ddcc47-2018-4cdf-9578-08151bc67a0a")]
            public virtual Ranorex.DivTag Btn_SearchCountry
            {
                get
                {
                    return _btn_searchcountryInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Btn_SearchCountry item info.
            /// </summary>
            [RepositoryItemInfo("e6ddcc47-2018-4cdf-9578-08151bc67a0a")]
            public virtual RepoItemInfo Btn_SearchCountryInfo
            {
                get
                {
                    return _btn_searchcountryInfo;
                }
            }
        }

        /// <summary>
        /// The LoginToYourAccountLogOnAppFolder folder.
        /// </summary>
        [RepositoryFolder("b0a24bd6-756d-4068-a148-1e7c7f7ce207")]
        public partial class LoginToYourAccountLogOnAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txt_usernameInfo;
            RepoItemInfo _txt_passwordInfo;
            RepoItemInfo _btn_logonInfo;

            /// <summary>
            /// Creates a new LoginToYourAccountLogOn  folder.
            /// </summary>
            public LoginToYourAccountLogOnAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginToYourAccountLogOn", "/dom[@domain='aecawiatr.accounts.ondemand.com']", parentFolder, 30000, null, false, "b0a24bd6-756d-4068-a148-1e7c7f7ce207", "")
            {
                _txt_usernameInfo = new RepoItemInfo(this, "txt_Username", ".//input[#'j_username']", ".//input[#'j_username']", 30000, null, "8d7417e9-0f06-4e82-bcd6-407af2c4c4f3");
                _txt_passwordInfo = new RepoItemInfo(this, "txt_Password", ".//input[#'j_password']", ".//input[#'j_password']", 30000, null, "6e2202d6-0431-4c56-9ecc-73b9aea63ffe");
                _btn_logonInfo = new RepoItemInfo(this, "Btn_LogOn", ".//button[#'logOnFormSubmit']", ".//button[#'logOnFormSubmit']", 30000, null, "8d658e73-a943-4565-b8cd-ab5746286202");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b0a24bd6-756d-4068-a148-1e7c7f7ce207")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b0a24bd6-756d-4068-a148-1e7c7f7ce207")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txt_Username item.
            /// </summary>
            [RepositoryItem("8d7417e9-0f06-4e82-bcd6-407af2c4c4f3")]
            public virtual Ranorex.InputTag txt_Username
            {
                get
                {
                    return _txt_usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_Username item info.
            /// </summary>
            [RepositoryItemInfo("8d7417e9-0f06-4e82-bcd6-407af2c4c4f3")]
            public virtual RepoItemInfo txt_UsernameInfo
            {
                get
                {
                    return _txt_usernameInfo;
                }
            }

            /// <summary>
            /// The txt_Password item.
            /// </summary>
            [RepositoryItem("6e2202d6-0431-4c56-9ecc-73b9aea63ffe")]
            public virtual Ranorex.InputTag txt_Password
            {
                get
                {
                    return _txt_passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txt_Password item info.
            /// </summary>
            [RepositoryItemInfo("6e2202d6-0431-4c56-9ecc-73b9aea63ffe")]
            public virtual RepoItemInfo txt_PasswordInfo
            {
                get
                {
                    return _txt_passwordInfo;
                }
            }

            /// <summary>
            /// The Btn_LogOn item.
            /// </summary>
            [RepositoryItem("8d658e73-a943-4565-b8cd-ab5746286202")]
            public virtual Ranorex.ButtonTag Btn_LogOn
            {
                get
                {
                    return _btn_logonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Btn_LogOn item info.
            /// </summary>
            [RepositoryItemInfo("8d658e73-a943-4565-b8cd-ab5746286202")]
            public virtual RepoItemInfo Btn_LogOnInfo
            {
                get
                {
                    return _btn_logonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
