///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace D4H_BP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SubmitOT recording.
    /// </summary>
    [TestModule("a3a624cc-f2be-4960-a8fe-475440af6808", ModuleType.Recording, 1)]
    public partial class SubmitOT : ITestModule
    {
        /// <summary>
        /// Holds an instance of the D4H_BPRepository repository.
        /// </summary>
        public static D4H_BPRepository repo = D4H_BPRepository.Instance;

        static SubmitOT instance = new SubmitOT();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SubmitOT()
        {
            varGetCRString = "";
            varGetCRNumber = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SubmitOT Instance
        {
            get { return instance; }
        }

#region Variables

        string _varGetCRString;

        /// <summary>
        /// Gets or sets the value of variable varGetCRString.
        /// </summary>
        [TestVariable("2a9e2ac7-c97f-450d-812d-12e1f4fa7f8d")]
        public string varGetCRString
        {
            get { return _varGetCRString; }
            set { _varGetCRString = value; }
        }

        string _varGetCRNumber;

        /// <summary>
        /// Gets or sets the value of variable varGetCRNumber.
        /// </summary>
        [TestVariable("53199d6e-7f05-4eb6-a774-57280a2922e4")]
        public string varGetCRNumber
        {
            get { return _varGetCRNumber; }
            set { _varGetCRNumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable domainname.
        /// </summary>
        [TestVariable("a17ded76-ebae-484c-b62c-6174d0eef3d4")]
        public string domainname
        {
            get { return repo.domainname; }
            set { repo.domainname = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Btn_SubmitOT' at Center.", repo.ApplicationUnderTest.Btn_SubmitOTInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Btn_SubmitOT.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_Note4Submit' at Center.", repo.ApplicationUnderTest.txt_Note4SubmitInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.txt_Note4Submit.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Please Submit!' with focus on 'ApplicationUnderTest.txt_Note4Submit'.", repo.ApplicationUnderTest.txt_Note4SubmitInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.txt_Note4Submit.PressKeys("Please Submit!");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Btn_Submit' at Center.", repo.ApplicationUnderTest.Btn_SubmitInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Btn_Submit.Click();
            Delay.Milliseconds(0);
            
            Get_value_lb_RequestwithCR(repo.ApplicationUnderTest.lb_RequestwithCRInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Btn_OKRequestSuccess' at Center.", repo.ApplicationUnderTest.Btn_OKRequestSuccessInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Btn_OKRequestSuccess.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_ChangeRequestFilter' at Center.", repo.ApplicationUnderTest.txt_ChangeRequestFilterInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.txt_ChangeRequestFilter.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varGetCRNumber' with focus on 'ApplicationUnderTest.txt_ChangeRequestFilter'.", repo.ApplicationUnderTest.txt_ChangeRequestFilterInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.txt_ChangeRequestFilter.PressKeys(varGetCRNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Btn_OKFilter' at Center.", repo.ApplicationUnderTest.Btn_OKFilterInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.Btn_OKFilter.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
