///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Manual1809_ZEBA_BD1.Requestor.InputData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InputHeader recording.
    /// </summary>
    [TestModule("8c47fbde-1a4e-4005-a5a9-17fb3e5562a0", ModuleType.Recording, 1)]
    public partial class InputHeader : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Manual1809_ZEBA_BD1.Manual1809_ZB02_VD_GD1Repository repository.
        /// </summary>
        public static global::Manual1809_ZEBA_BD1.Manual1809_ZB02_VD_GD1Repository repo = global::Manual1809_ZEBA_BD1.Manual1809_ZB02_VD_GD1Repository.Instance;

        static InputHeader instance = new InputHeader();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InputHeader()
        {
            varHeaderDescription = "";
            varHeaderPriority = "";
            varHeaderReason = "";
            varHeaderOtherReason = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InputHeader Instance
        {
            get { return instance; }
        }

#region Variables

        string _varHeaderDescription;

        /// <summary>
        /// Gets or sets the value of variable varHeaderDescription.
        /// </summary>
        [TestVariable("600350f5-9088-4fb9-826d-9ee9b13c54af")]
        public string varHeaderDescription
        {
            get { return _varHeaderDescription; }
            set { _varHeaderDescription = value; }
        }

        string _varHeaderPriority;

        /// <summary>
        /// Gets or sets the value of variable varHeaderPriority.
        /// </summary>
        [TestVariable("88326151-863a-42e3-9a67-571f6d3bc2a7")]
        public string varHeaderPriority
        {
            get { return _varHeaderPriority; }
            set { _varHeaderPriority = value; }
        }

        string _varHeaderReason;

        /// <summary>
        /// Gets or sets the value of variable varHeaderReason.
        /// </summary>
        [TestVariable("95197e42-a638-421b-a905-bca44db49c3c")]
        public string varHeaderReason
        {
            get { return _varHeaderReason; }
            set { _varHeaderReason = value; }
        }

        string _varHeaderOtherReason;

        /// <summary>
        /// Gets or sets the value of variable varHeaderOtherReason.
        /// </summary>
        [TestVariable("4dab3ed0-f015-4597-8bf0-c35931be6320")]
        public string varHeaderOtherReason
        {
            get { return _varHeaderOtherReason; }
            set { _varHeaderOtherReason = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputHeader.txt_RequestDescription' at Center.", repo.Manual1809_Chrome.InputHeader.txt_RequestDescriptionInfo, new RecordItemIndex(0));
            repo.Manual1809_Chrome.InputHeader.txt_RequestDescription.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varHeaderDescription' with focus on 'Manual1809_Chrome.InputHeader.txt_RequestDescription'.", repo.Manual1809_Chrome.InputHeader.txt_RequestDescriptionInfo, new RecordItemIndex(1));
            repo.Manual1809_Chrome.InputHeader.txt_RequestDescription.PressKeys(varHeaderDescription);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputHeader.txt_Priority' at Center.", repo.Manual1809_Chrome.InputHeader.txt_PriorityInfo, new RecordItemIndex(2));
            repo.Manual1809_Chrome.InputHeader.txt_Priority.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varHeaderPriority' with focus on 'Manual1809_Chrome.InputHeader.txt_Priority'.", repo.Manual1809_Chrome.InputHeader.txt_PriorityInfo, new RecordItemIndex(3));
            repo.Manual1809_Chrome.InputHeader.txt_Priority.PressKeys(varHeaderPriority);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputHeader.txt_Reason' at Center.", repo.Manual1809_Chrome.InputHeader.txt_ReasonInfo, new RecordItemIndex(4));
            repo.Manual1809_Chrome.InputHeader.txt_Reason.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varHeaderReason' with focus on 'Manual1809_Chrome.InputHeader.txt_Reason'.", repo.Manual1809_Chrome.InputHeader.txt_ReasonInfo, new RecordItemIndex(5));
            repo.Manual1809_Chrome.InputHeader.txt_Reason.PressKeys(varHeaderReason);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputHeader.txt_OtherReason' at Center.", repo.Manual1809_Chrome.InputHeader.txt_OtherReasonInfo, new RecordItemIndex(6));
            repo.Manual1809_Chrome.InputHeader.txt_OtherReason.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varHeaderOtherReason' with focus on 'Manual1809_Chrome.InputHeader.txt_OtherReason'.", repo.Manual1809_Chrome.InputHeader.txt_OtherReasonInfo, new RecordItemIndex(7));
            repo.Manual1809_Chrome.InputHeader.txt_OtherReason.PressKeys(varHeaderOtherReason);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
