///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Manual1809_ZEBA_BD1.Requestor.InputData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InputProductMin recording.
    /// </summary>
    [TestModule("262d0ece-2b6d-4fe5-a64a-7494f2dd315b", ModuleType.Recording, 1)]
    public partial class InputProductMin : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Manual1809_ZEBA_BD1.Manual1809_ZB02_VD_GD1Repository repository.
        /// </summary>
        public static global::Manual1809_ZEBA_BD1.Manual1809_ZB02_VD_GD1Repository repo = global::Manual1809_ZEBA_BD1.Manual1809_ZB02_VD_GD1Repository.Instance;

        static InputProductMin instance = new InputProductMin();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InputProductMin()
        {
            varCategory = "";
            varTitle = "";
            varOrgBPName1 = "";
            varOrgBPName2 = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InputProductMin Instance
        {
            get { return instance; }
        }

#region Variables

        string _varCategory;

        /// <summary>
        /// Gets or sets the value of variable varCategory.
        /// </summary>
        [TestVariable("aa376a3e-e341-4021-963c-8d952a94846a")]
        public string varCategory
        {
            get { return _varCategory; }
            set { _varCategory = value; }
        }

        string _varTitle;

        /// <summary>
        /// Gets or sets the value of variable varTitle.
        /// </summary>
        [TestVariable("36a2b216-35cc-4437-91ee-2329fec76a10")]
        public string varTitle
        {
            get { return _varTitle; }
            set { _varTitle = value; }
        }

        string _varOrgBPName1;

        /// <summary>
        /// Gets or sets the value of variable varOrgBPName1.
        /// </summary>
        [TestVariable("52b1f3a6-bc60-4688-a0c2-85fdb30a8d54")]
        public string varOrgBPName1
        {
            get { return _varOrgBPName1; }
            set { _varOrgBPName1 = value; }
        }

        string _varOrgBPName2;

        /// <summary>
        /// Gets or sets the value of variable varOrgBPName2.
        /// </summary>
        [TestVariable("692397f6-e654-4b4f-9c8d-e58863d5ca8d")]
        public string varOrgBPName2
        {
            get { return _varOrgBPName2; }
            set { _varOrgBPName2 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputGeneralData.lb_SelectGeneralData' at Center.", repo.Manual1809_Chrome.InputGeneralData.lb_SelectGeneralDataInfo, new RecordItemIndex(0));
            repo.Manual1809_Chrome.InputGeneralData.lb_SelectGeneralData.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputGeneralData.txt_Category' at Center.", repo.Manual1809_Chrome.InputGeneralData.txt_CategoryInfo, new RecordItemIndex(1));
            repo.Manual1809_Chrome.InputGeneralData.txt_Category.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varCategory' with focus on 'Manual1809_Chrome.InputGeneralData.txt_Category'.", repo.Manual1809_Chrome.InputGeneralData.txt_CategoryInfo, new RecordItemIndex(2));
            repo.Manual1809_Chrome.InputGeneralData.txt_Category.PressKeys(varCategory);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputGeneralData.txt_Title' at Center.", repo.Manual1809_Chrome.InputGeneralData.txt_TitleInfo, new RecordItemIndex(3));
            repo.Manual1809_Chrome.InputGeneralData.txt_Title.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varTitle' with focus on 'Manual1809_Chrome.InputGeneralData.txt_Title'.", repo.Manual1809_Chrome.InputGeneralData.txt_TitleInfo, new RecordItemIndex(4));
            repo.Manual1809_Chrome.InputGeneralData.txt_Title.PressKeys(varTitle);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputGeneralData.txt_OrgBPName1' at Center.", repo.Manual1809_Chrome.InputGeneralData.txt_OrgBPName1Info, new RecordItemIndex(5));
            repo.Manual1809_Chrome.InputGeneralData.txt_OrgBPName1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varOrgBPName1' with focus on 'Manual1809_Chrome.InputGeneralData.txt_OrgBPName1'.", repo.Manual1809_Chrome.InputGeneralData.txt_OrgBPName1Info, new RecordItemIndex(6));
            repo.Manual1809_Chrome.InputGeneralData.txt_OrgBPName1.PressKeys(varOrgBPName1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputGeneralData.txt_OrgBPName2' at Center.", repo.Manual1809_Chrome.InputGeneralData.txt_OrgBPName2Info, new RecordItemIndex(7));
            repo.Manual1809_Chrome.InputGeneralData.txt_OrgBPName2.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varOrgBPName2' with focus on 'Manual1809_Chrome.InputGeneralData.txt_OrgBPName2'.", repo.Manual1809_Chrome.InputGeneralData.txt_OrgBPName2Info, new RecordItemIndex(8));
            repo.Manual1809_Chrome.InputGeneralData.txt_OrgBPName2.PressKeys(varOrgBPName2);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
