///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Manual1809_ZEBA_BD1.Requestor.InputData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InputBasicData recording.
    /// </summary>
    [TestModule("c257dfa3-3c11-47c6-a7dd-89593832ae9f", ModuleType.Recording, 1)]
    public partial class InputBasicData : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Manual1809_ZEBA_BD1.Manual1809_ZB02_VD_GD1Repository repository.
        /// </summary>
        public static global::Manual1809_ZEBA_BD1.Manual1809_ZB02_VD_GD1Repository repo = global::Manual1809_ZEBA_BD1.Manual1809_ZB02_VD_GD1Repository.Instance;

        static InputBasicData instance = new InputBasicData();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InputBasicData()
        {
            varPostalCode = "";
            varCity = "";
            varRegion = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InputBasicData Instance
        {
            get { return instance; }
        }

#region Variables

        string _varPostalCode;

        /// <summary>
        /// Gets or sets the value of variable varPostalCode.
        /// </summary>
        [TestVariable("5d1161b7-e1e0-43b1-830b-0ebfabcb2ae4")]
        public string varPostalCode
        {
            get { return _varPostalCode; }
            set { _varPostalCode = value; }
        }

        string _varCity;

        /// <summary>
        /// Gets or sets the value of variable varCity.
        /// </summary>
        [TestVariable("895f48e6-328e-41cd-a756-42855962316c")]
        public string varCity
        {
            get { return _varCity; }
            set { _varCity = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varRegion.
        /// </summary>
        [TestVariable("acb197e6-e976-453b-bba9-61c3287f8968")]
        public string varRegion
        {
            get { return repo.varRegion; }
            set { repo.varRegion = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputAddress.lb_Address' at Center.", repo.Manual1809_Chrome.InputAddress.lb_AddressInfo, new RecordItemIndex(0));
            repo.Manual1809_Chrome.InputAddress.lb_Address.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputAddress.txt_PostalCode' at Center.", repo.Manual1809_Chrome.InputAddress.txt_PostalCodeInfo, new RecordItemIndex(1));
            repo.Manual1809_Chrome.InputAddress.txt_PostalCode.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varPostalCode' with focus on 'Manual1809_Chrome.InputAddress.txt_PostalCode'.", repo.Manual1809_Chrome.InputAddress.txt_PostalCodeInfo, new RecordItemIndex(2));
            repo.Manual1809_Chrome.InputAddress.txt_PostalCode.PressKeys(varPostalCode);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputAddress.txt_City' at Center.", repo.Manual1809_Chrome.InputAddress.txt_CityInfo, new RecordItemIndex(3));
            repo.Manual1809_Chrome.InputAddress.txt_City.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varCity' with focus on 'Manual1809_Chrome.InputAddress.txt_City'.", repo.Manual1809_Chrome.InputAddress.txt_CityInfo, new RecordItemIndex(4));
            repo.Manual1809_Chrome.InputAddress.txt_City.PressKeys(varCity);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputAddress.btn_Region' at Center.", repo.Manual1809_Chrome.InputAddress.btn_RegionInfo, new RecordItemIndex(5));
            repo.Manual1809_Chrome.InputAddress.btn_Region.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputAddress.txt_SearchRegion' at Center.", repo.Manual1809_Chrome.InputAddress.txt_SearchRegionInfo, new RecordItemIndex(6));
            repo.Manual1809_Chrome.InputAddress.txt_SearchRegion.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varRegion' with focus on 'Manual1809_Chrome.InputAddress.txt_SearchRegion'.", repo.Manual1809_Chrome.InputAddress.txt_SearchRegionInfo, new RecordItemIndex(7));
            repo.Manual1809_Chrome.InputAddress.txt_SearchRegion.PressKeys(varRegion);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputAddress.btn_SearchAction' at Center.", repo.Manual1809_Chrome.InputAddress.btn_SearchActionInfo, new RecordItemIndex(8));
            repo.Manual1809_Chrome.InputAddress.btn_SearchAction.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputAddress.lb_SelectRegion' at Center.", repo.Manual1809_Chrome.InputAddress.lb_SelectRegionInfo, new RecordItemIndex(9));
            repo.Manual1809_Chrome.InputAddress.lb_SelectRegion.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
