///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DemoOnSAP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording3 recording.
    /// </summary>
    [TestModule("469dad80-791e-4c3a-85ea-8506a3db1156", ModuleType.Recording, 1)]
    public partial class Recording3 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DemoOnSAPRepository repository.
        /// </summary>
        public static DemoOnSAPRepository repo = DemoOnSAPRepository.Instance;

        static Recording3 instance = new Recording3();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording3()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording3 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormSAP.txt_Client' at 3;8.", repo.FormSAP.txt_ClientInfo, new RecordItemIndex(0));
            repo.FormSAP.txt_Client.Click("3;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '110' with focus on 'FormSAP.txt_Client'.", repo.FormSAP.txt_ClientInfo, new RecordItemIndex(1));
            repo.FormSAP.txt_Client.PressKeys("110");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormSAP.txt_Username' at 17;6.", repo.FormSAP.txt_UsernameInfo, new RecordItemIndex(2));
            repo.FormSAP.txt_Username.Click("17;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'hnguyen02' with focus on 'FormSAP.txt_Username'.", repo.FormSAP.txt_UsernameInfo, new RecordItemIndex(3));
            repo.FormSAP.txt_Username.PressKeys("hnguyen02");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormSAP.RSYSTBCODE' at 3;7.", repo.FormSAP.RSYSTBCODEInfo, new RecordItemIndex(4));
            repo.FormSAP.RSYSTBCODE.Click("3;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '151325' with focus on 'FormSAP.RSYSTBCODE'.", repo.FormSAP.RSYSTBCODEInfo, new RecordItemIndex(5));
            repo.FormSAP.RSYSTBCODE.PressKeys("151325");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormSAP.Btn0' at 8;13.", repo.FormSAP.Btn0Info, new RecordItemIndex(6));
            repo.FormSAP.Btn0.Click("8;13");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
