///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Manual1809_ZEBA_BD1.Approval.ReviewAction
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ApprovalARequest recording.
    /// </summary>
    [TestModule("f073e1b5-9e8a-4ce6-9823-e282c55a76b1", ModuleType.Recording, 1)]
    public partial class ApprovalARequest : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Manual1809_ZEBA_BD1.Manual1809_ZB02_VD_GD1Repository repository.
        /// </summary>
        public static global::Manual1809_ZEBA_BD1.Manual1809_ZB02_VD_GD1Repository repo = global::Manual1809_ZEBA_BD1.Manual1809_ZB02_VD_GD1Repository.Instance;

        static ApprovalARequest instance = new ApprovalARequest();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ApprovalARequest()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ApprovalARequest Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(0));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Firefox.ReviewARequest.lb_SelectSearchRequest' at Center.", repo.Manual1809_Firefox.ReviewARequest.lb_SelectSearchRequestInfo, new RecordItemIndex(1));
            repo.Manual1809_Firefox.ReviewARequest.lb_SelectSearchRequest.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(2));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Firefox.ReviewARequest.lb_ApproveAction' at Center.", repo.Manual1809_Firefox.ReviewARequest.lb_ApproveActionInfo, new RecordItemIndex(3));
            repo.Manual1809_Firefox.ReviewARequest.lb_ApproveAction.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Firefox.ReviewARequest.txt_ApprovaRequestDescription' at Center.", repo.Manual1809_Firefox.ReviewARequest.txt_ApprovaRequestDescriptionInfo, new RecordItemIndex(4));
            repo.Manual1809_Firefox.ReviewARequest.txt_ApprovaRequestDescription.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Approved!' with focus on 'Manual1809_Firefox.ReviewARequest.txt_ApprovaRequestDescription'.", repo.Manual1809_Firefox.ReviewARequest.txt_ApprovaRequestDescriptionInfo, new RecordItemIndex(5));
            repo.Manual1809_Firefox.ReviewARequest.txt_ApprovaRequestDescription.PressKeys("Approved!");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Firefox.ReviewARequest.btn_ApproveAction' at Center.", repo.Manual1809_Firefox.ReviewARequest.btn_ApproveActionInfo, new RecordItemIndex(6));
            repo.Manual1809_Firefox.ReviewARequest.btn_ApproveAction.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
