///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Manual1809_ZEBA_BD1.Requestor.CommonAction
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SubmitRequest recording.
    /// </summary>
    [TestModule("d8c7b7b5-c601-4d94-bc14-d00f76a6d4ef", ModuleType.Recording, 1)]
    public partial class SubmitRequest : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Manual1809_ZEBA_BD1.Manual1809_ZB02_VD_GD1Repository repository.
        /// </summary>
        public static global::Manual1809_ZEBA_BD1.Manual1809_ZB02_VD_GD1Repository repo = global::Manual1809_ZEBA_BD1.Manual1809_ZB02_VD_GD1Repository.Instance;

        static SubmitRequest instance = new SubmitRequest();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SubmitRequest()
        {
            varObjType = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SubmitRequest Instance
        {
            get { return instance; }
        }

#region Variables

        string _varObjType;

        /// <summary>
        /// Gets or sets the value of variable varObjType.
        /// </summary>
        [TestVariable("e71d6155-51d2-4751-93f6-e14e3bd0274d")]
        public string varObjType
        {
            get { return _varObjType; }
            set { _varObjType = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'Manual1809_Chrome.SubmitRequest.btn_SubmitRequest'", repo.Manual1809_Chrome.SubmitRequest.btn_SubmitRequestInfo, new ActionTimeout(5000), new RecordItemIndex(0));
            repo.Manual1809_Chrome.SubmitRequest.btn_SubmitRequestInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.SubmitRequest.btn_SubmitRequest' at Center.", repo.Manual1809_Chrome.SubmitRequest.btn_SubmitRequestInfo, new RecordItemIndex(1));
            repo.Manual1809_Chrome.SubmitRequest.btn_SubmitRequest.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.SubmitRequest.txt_SearchObjectType' at Center.", repo.Manual1809_Chrome.SubmitRequest.txt_SearchObjectTypeInfo, new RecordItemIndex(2));
            repo.Manual1809_Chrome.SubmitRequest.txt_SearchObjectType.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varObjType' with focus on 'Manual1809_Chrome.SubmitRequest.txt_SearchObjectType'.", repo.Manual1809_Chrome.SubmitRequest.txt_SearchObjectTypeInfo, new RecordItemIndex(3));
            repo.Manual1809_Chrome.SubmitRequest.txt_SearchObjectType.PressKeys(varObjType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.SubmitRequest.btn_NextAction' at Center.", repo.Manual1809_Chrome.SubmitRequest.btn_NextActionInfo, new RecordItemIndex(4));
            repo.Manual1809_Chrome.SubmitRequest.btn_NextAction.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
