///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Manual1809_ZEBA_BD1.Approval.CommonAction
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FilterCR_Approval recording.
    /// </summary>
    [TestModule("0ac498bd-7a54-4b56-b52f-3f3c2b569c85", ModuleType.Recording, 1)]
    public partial class FilterCR_Approval : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Manual1809_ZEBA_BD1.Manual1809_ZEBA_BD1Repository repository.
        /// </summary>
        public static global::Manual1809_ZEBA_BD1.Manual1809_ZEBA_BD1Repository repo = global::Manual1809_ZEBA_BD1.Manual1809_ZEBA_BD1Repository.Instance;

        static FilterCR_Approval instance = new FilterCR_Approval();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FilterCR_Approval()
        {
            varCRnumber = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FilterCR_Approval Instance
        {
            get { return instance; }
        }

#region Variables

        string _varCRnumber;

        /// <summary>
        /// Gets or sets the value of variable varCRnumber.
        /// </summary>
        [TestVariable("9073fce0-3df3-4720-b72e-809b5be38409")]
        public string varCRnumber
        {
            get { return _varCRnumber; }
            set { _varCRnumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Firefox.CommondElements.txt_SearchCR' at Center.", repo.Manual1809_Firefox.CommondElements.txt_SearchCRInfo, new RecordItemIndex(0));
            repo.Manual1809_Firefox.CommondElements.txt_SearchCR.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varCRnumber' with focus on 'Manual1809_Firefox.CommondElements.txt_SearchCR'.", repo.Manual1809_Firefox.CommondElements.txt_SearchCRInfo, new RecordItemIndex(1));
            repo.Manual1809_Firefox.CommondElements.txt_SearchCR.PressKeys(varCRnumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Firefox.CommondElements.Btn_GoAction' at Center.", repo.Manual1809_Firefox.CommondElements.Btn_GoActionInfo, new RecordItemIndex(2));
            repo.Manual1809_Firefox.CommondElements.Btn_GoAction.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
