///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Manual1809_ZEBA_BD1.Approval.CommonAction
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login_Approval recording.
    /// </summary>
    [TestModule("90686ffa-a65e-4f96-964d-f4c9a50f5498", ModuleType.Recording, 1)]
    public partial class Login_Approval : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Manual1809_ZEBA_BD1.Manual1809_ZEBA_BD1Repository repository.
        /// </summary>
        public static global::Manual1809_ZEBA_BD1.Manual1809_ZEBA_BD1Repository repo = global::Manual1809_ZEBA_BD1.Manual1809_ZEBA_BD1Repository.Instance;

        static Login_Approval instance = new Login_Approval();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login_Approval()
        {
            varUsernameAppro = "";
            varPasswordAppro = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login_Approval Instance
        {
            get { return instance; }
        }

#region Variables

        string _varUsernameAppro;

        /// <summary>
        /// Gets or sets the value of variable varUsernameAppro.
        /// </summary>
        [TestVariable("3e8ffe4a-deb5-4092-b122-dc4cd1b4ad88")]
        public string varUsernameAppro
        {
            get { return _varUsernameAppro; }
            set { _varUsernameAppro = value; }
        }

        string _varPasswordAppro;

        /// <summary>
        /// Gets or sets the value of variable varPasswordAppro.
        /// </summary>
        [TestVariable("4839590c-f0e7-4504-87d5-19cee6980ba7")]
        public string varPasswordAppro
        {
            get { return _varPasswordAppro; }
            set { _varPasswordAppro = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginForm_Firefox.txt_Username' at Center.", repo.LoginForm_Firefox.txt_UsernameInfo, new RecordItemIndex(0));
            repo.LoginForm_Firefox.txt_Username.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varUsernameAppro' with focus on 'LoginForm_Firefox.txt_Username'.", repo.LoginForm_Firefox.txt_UsernameInfo, new RecordItemIndex(1));
            repo.LoginForm_Firefox.txt_Username.PressKeys(varUsernameAppro);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginForm_Firefox.txt_Password' at Center.", repo.LoginForm_Firefox.txt_PasswordInfo, new RecordItemIndex(2));
            repo.LoginForm_Firefox.txt_Password.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varPasswordAppro' with focus on 'LoginForm_Firefox.txt_Password'.", repo.LoginForm_Firefox.txt_PasswordInfo, new RecordItemIndex(3));
            repo.LoginForm_Firefox.txt_Password.PressKeys(varPasswordAppro);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginForm_Firefox.btn_LogOn' at Center.", repo.LoginForm_Firefox.btn_LogOnInfo, new RecordItemIndex(4));
            repo.LoginForm_Firefox.btn_LogOn.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
