///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace rx_git
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("8abfbace-55ea-47b4-90cf-2c5f1617a00a", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the rx_gitRepository repository.
        /// </summary>
        public static rx_gitRepository repo = rx_gitRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginToYourAccountLogOn.JUsername' at Center.", repo.LoginToYourAccountLogOn.JUsernameInfo, new RecordItemIndex(0));
            repo.LoginToYourAccountLogOn.JUsername.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'P000020' with focus on 'LoginToYourAccountLogOn.JUsername'.", repo.LoginToYourAccountLogOn.JUsernameInfo, new RecordItemIndex(1));
            repo.LoginToYourAccountLogOn.JUsername.PressKeys("P000020");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginToYourAccountLogOn.JPassword' at Center.", repo.LoginToYourAccountLogOn.JPasswordInfo, new RecordItemIndex(2));
            repo.LoginToYourAccountLogOn.JPassword.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'VNSAP2022!' with focus on 'LoginToYourAccountLogOn.JPassword'.", repo.LoginToYourAccountLogOn.JPasswordInfo, new RecordItemIndex(3));
            repo.LoginToYourAccountLogOn.JPassword.PressKeys("VNSAP2022!");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginToYourAccountLogOn.LogOn' at Center.", repo.LoginToYourAccountLogOn.LogOnInfo, new RecordItemIndex(4));
            repo.LoginToYourAccountLogOn.LogOn.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Welcome.MainApp' at Center.", repo.Welcome.MainAppInfo, new RecordItemIndex(5));
            repo.Welcome.MainApp.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
