///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace rx_git
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the rx_gitRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("41fae5e4-a9b7-42e1-887a-f4768c410aa9")]
    public partial class rx_gitRepository : RepoGenBaseFolder
    {
        static rx_gitRepository instance = new rx_gitRepository();
        rx_gitRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        rx_gitRepositoryFolders.LoginToYourAccountLogOnAppFolder _logintoyouraccountlogon;

        /// <summary>
        /// Gets the singleton class instance representing the rx_gitRepository element repository.
        /// </summary>
        [RepositoryFolder("41fae5e4-a9b7-42e1-887a-f4768c410aa9")]
        public static rx_gitRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public rx_gitRepository() 
            : base("rx_gitRepository", "/", null, 0, false, "41fae5e4-a9b7-42e1-887a-f4768c410aa9", ".\\RepositoryImages\\rx_gitRepository41fae5e4.rximgres")
        {
            _applicationundertest = new rx_gitRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _logintoyouraccountlogon = new rx_gitRepositoryFolders.LoginToYourAccountLogOnAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("41fae5e4-a9b7-42e1-887a-f4768c410aa9")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("5f44bf1d-7220-445c-9f61-4197ac062486")]
        public virtual rx_gitRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The LoginToYourAccountLogOn folder.
        /// </summary>
        [RepositoryFolder("3d437914-4129-4cf9-bf80-3f8eb3e0c9a4")]
        public virtual rx_gitRepositoryFolders.LoginToYourAccountLogOnAppFolder LoginToYourAccountLogOn
        {
            get { return _logintoyouraccountlogon; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class rx_gitRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("5f44bf1d-7220-445c-9f61-4197ac062486")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='manual-test-ecc-simplemdg-web.cfapps.eu10.hana.ondemand.com']", parentFolder, 30000, null, false, "5f44bf1d-7220-445c-9f61-4197ac062486", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5f44bf1d-7220-445c-9f61-4197ac062486")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5f44bf1d-7220-445c-9f61-4197ac062486")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The LoginToYourAccountLogOnAppFolder folder.
        /// </summary>
        [RepositoryFolder("3d437914-4129-4cf9-bf80-3f8eb3e0c9a4")]
        public partial class LoginToYourAccountLogOnAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _jusernameInfo;
            RepoItemInfo _jpasswordInfo;
            RepoItemInfo _logonInfo;

            /// <summary>
            /// Creates a new LoginToYourAccountLogOn  folder.
            /// </summary>
            public LoginToYourAccountLogOnAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginToYourAccountLogOn", "/dom[@domain='aecawiatr.accounts.ondemand.com']", parentFolder, 30000, null, false, "3d437914-4129-4cf9-bf80-3f8eb3e0c9a4", "")
            {
                _jusernameInfo = new RepoItemInfo(this, "JUsername", ".//input[#'j_username']", ".//input[#'j_username']", 30000, null, "bd3d784d-c7cb-48e4-b798-d399d59f4f0c");
                _jpasswordInfo = new RepoItemInfo(this, "JPassword", ".//input[#'j_password']", ".//input[#'j_password']", 30000, null, "c0884876-1032-4922-9735-ddb68147ace9");
                _logonInfo = new RepoItemInfo(this, "LogOn", ".//button[#'logOnFormSubmit']/div[@innertext='Log On']", ".//button[#'logOnFormSubmit']/div[@innertext='Log On']", 30000, null, "5355c27c-9402-4e2e-ae1a-ecb54eda3de4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3d437914-4129-4cf9-bf80-3f8eb3e0c9a4")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3d437914-4129-4cf9-bf80-3f8eb3e0c9a4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The JUsername item.
            /// </summary>
            [RepositoryItem("bd3d784d-c7cb-48e4-b798-d399d59f4f0c")]
            public virtual Ranorex.InputTag JUsername
            {
                get
                {
                    return _jusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The JUsername item info.
            /// </summary>
            [RepositoryItemInfo("bd3d784d-c7cb-48e4-b798-d399d59f4f0c")]
            public virtual RepoItemInfo JUsernameInfo
            {
                get
                {
                    return _jusernameInfo;
                }
            }

            /// <summary>
            /// The JPassword item.
            /// </summary>
            [RepositoryItem("c0884876-1032-4922-9735-ddb68147ace9")]
            public virtual Ranorex.InputTag JPassword
            {
                get
                {
                    return _jpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The JPassword item info.
            /// </summary>
            [RepositoryItemInfo("c0884876-1032-4922-9735-ddb68147ace9")]
            public virtual RepoItemInfo JPasswordInfo
            {
                get
                {
                    return _jpasswordInfo;
                }
            }

            /// <summary>
            /// The LogOn item.
            /// </summary>
            [RepositoryItem("5355c27c-9402-4e2e-ae1a-ecb54eda3de4")]
            public virtual Ranorex.DivTag LogOn
            {
                get
                {
                    return _logonInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The LogOn item info.
            /// </summary>
            [RepositoryItemInfo("5355c27c-9402-4e2e-ae1a-ecb54eda3de4")]
            public virtual RepoItemInfo LogOnInfo
            {
                get
                {
                    return _logonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
