///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Manual1809_ZEBA_BD1.Requestor.InputData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InputProductMin recording.
    /// </summary>
    [TestModule("262d0ece-2b6d-4fe5-a64a-7494f2dd315b", ModuleType.Recording, 1)]
    public partial class InputProductMin : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Manual1809_ZEBA_BD1.Manual1809_ZEBA_BD1Repository repository.
        /// </summary>
        public static global::Manual1809_ZEBA_BD1.Manual1809_ZEBA_BD1Repository repo = global::Manual1809_ZEBA_BD1.Manual1809_ZEBA_BD1Repository.Instance;

        static InputProductMin instance = new InputProductMin();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InputProductMin()
        {
            varMaterialDescript = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InputProductMin Instance
        {
            get { return instance; }
        }

#region Variables

        string _varMaterialDescript;

        /// <summary>
        /// Gets or sets the value of variable varMaterialDescript.
        /// </summary>
        [TestVariable("401552ee-0042-45f6-b97c-849b45174abc")]
        public string varMaterialDescript
        {
            get { return _varMaterialDescript; }
            set { _varMaterialDescript = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputProduct.btn_AddLang' at Center.", repo.Manual1809_Chrome.InputProduct.btn_AddLangInfo, new RecordItemIndex(0));
            repo.Manual1809_Chrome.InputProduct.btn_AddLang.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputProduct.txt_MaterialDescription' at Center.", repo.Manual1809_Chrome.InputProduct.txt_MaterialDescriptionInfo, new RecordItemIndex(1));
            repo.Manual1809_Chrome.InputProduct.txt_MaterialDescription.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varMaterialDescript' with focus on 'Manual1809_Chrome.InputProduct.txt_MaterialDescription'.", repo.Manual1809_Chrome.InputProduct.txt_MaterialDescriptionInfo, new RecordItemIndex(2));
            repo.Manual1809_Chrome.InputProduct.txt_MaterialDescription.PressKeys(varMaterialDescript);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputProduct.btn_AddAction' at Center.", repo.Manual1809_Chrome.InputProduct.btn_AddActionInfo, new RecordItemIndex(3));
            repo.Manual1809_Chrome.InputProduct.btn_AddAction.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
