///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Manual1809_ZEBA_BD1.Requestor.InputData
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InputBasicData recording.
    /// </summary>
    [TestModule("c257dfa3-3c11-47c6-a7dd-89593832ae9f", ModuleType.Recording, 1)]
    public partial class InputBasicData : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Manual1809_ZEBA_BD1.Manual1809_ZEBA_BD1Repository repository.
        /// </summary>
        public static global::Manual1809_ZEBA_BD1.Manual1809_ZEBA_BD1Repository repo = global::Manual1809_ZEBA_BD1.Manual1809_ZEBA_BD1Repository.Instance;

        static InputBasicData instance = new InputBasicData();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InputBasicData()
        {
            varProductGroup = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InputBasicData Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varProductGroup.
        /// </summary>
        [TestVariable("5d0ba8d4-07af-4450-83c9-d8a95982f8d9")]
        public string varProductGroup
        {
            get { return repo.varProductGroup; }
            set { repo.varProductGroup = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputBasicData.lb_BasicData' at Center.", repo.Manual1809_Chrome.InputBasicData.lb_BasicDataInfo, new RecordItemIndex(0));
            repo.Manual1809_Chrome.InputBasicData.lb_BasicData.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputBasicData.btn_ChooseMaterialGroup' at Center.", repo.Manual1809_Chrome.InputBasicData.btn_ChooseMaterialGroupInfo, new RecordItemIndex(1));
            repo.Manual1809_Chrome.InputBasicData.btn_ChooseMaterialGroup.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputBasicData.txt_SearchProductGroup' at Center.", repo.Manual1809_Chrome.InputBasicData.txt_SearchProductGroupInfo, new RecordItemIndex(2));
            repo.Manual1809_Chrome.InputBasicData.txt_SearchProductGroup.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varProductGroup' with focus on 'Manual1809_Chrome.InputBasicData.txt_SearchProductGroup'.", repo.Manual1809_Chrome.InputBasicData.txt_SearchProductGroupInfo, new RecordItemIndex(3));
            repo.Manual1809_Chrome.InputBasicData.txt_SearchProductGroup.PressKeys(varProductGroup);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputBasicData.btn_SearchAction' at Center.", repo.Manual1809_Chrome.InputBasicData.btn_SearchActionInfo, new RecordItemIndex(4));
            repo.Manual1809_Chrome.InputBasicData.btn_SearchAction.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.InputBasicData.lb_SelectProductGroup' at Center.", repo.Manual1809_Chrome.InputBasicData.lb_SelectProductGroupInfo, new RecordItemIndex(5));
            repo.Manual1809_Chrome.InputBasicData.lb_SelectProductGroup.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
