///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Manual1809_ZEBA_BD1.Steward
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FilterCR recording.
    /// </summary>
    [TestModule("0c1da331-89b0-4968-8be5-dd857ca7c08e", ModuleType.Recording, 1)]
    public partial class FilterCR : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Manual1809_ZEBA_BD1.Manual1809_ZEBA_BD1Repository repository.
        /// </summary>
        public static global::Manual1809_ZEBA_BD1.Manual1809_ZEBA_BD1Repository repo = global::Manual1809_ZEBA_BD1.Manual1809_ZEBA_BD1Repository.Instance;

        static FilterCR instance = new FilterCR();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FilterCR()
        {
            varCRNumber = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FilterCR Instance
        {
            get { return instance; }
        }

#region Variables

        string _varCRNumber;

        /// <summary>
        /// Gets or sets the value of variable varCRNumber.
        /// </summary>
        [TestVariable("9e3accee-6be8-4516-a167-af01c327771c")]
        public string varCRNumber
        {
            get { return _varCRNumber; }
            set { _varCRNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Firefox.Steward.txtSearchCR' at Center.", repo.Manual1809_Firefox.Steward.txtSearchCRInfo, new RecordItemIndex(0));
            repo.Manual1809_Firefox.Steward.txtSearchCR.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varCRNumber' with focus on 'Manual1809_Firefox.Steward.txtSearchCR'.", repo.Manual1809_Firefox.Steward.txtSearchCRInfo, new RecordItemIndex(1));
            repo.Manual1809_Firefox.Steward.txtSearchCR.PressKeys(varCRNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Firefox.Steward.Btn_GoAction' at Center.", repo.Manual1809_Firefox.Steward.Btn_GoActionInfo, new RecordItemIndex(2));
            repo.Manual1809_Firefox.Steward.Btn_GoAction.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
