///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Manual1809_ZEBA_BD1.Steward
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LogoutStewards recording.
    /// </summary>
    [TestModule("2a277ace-b6ce-428b-b4cf-a3a5240b5ab7", ModuleType.Recording, 1)]
    public partial class LogoutStewards : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Manual1809_ZEBA_BD1.Manual1809_ZB02_VD_GD1Repository repository.
        /// </summary>
        public static global::Manual1809_ZEBA_BD1.Manual1809_ZB02_VD_GD1Repository repo = global::Manual1809_ZEBA_BD1.Manual1809_ZB02_VD_GD1Repository.Instance;

        static LogoutStewards instance = new LogoutStewards();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LogoutStewards()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LogoutStewards Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Firefox.Steward.lb_StewardIcon' at Center.", repo.Manual1809_Firefox.Steward.lb_StewardIconInfo, new RecordItemIndex(0));
            repo.Manual1809_Firefox.Steward.lb_StewardIcon.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Firefox.Steward.lb_LogoutSteward' at Center.", repo.Manual1809_Firefox.Steward.lb_LogoutStewardInfo, new RecordItemIndex(1));
            repo.Manual1809_Firefox.Steward.lb_LogoutSteward.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Firefox.Steward.btn_YesConfirmLogout' at Center.", repo.Manual1809_Firefox.Steward.btn_YesConfirmLogoutInfo, new RecordItemIndex(2));
            repo.Manual1809_Firefox.Steward.btn_YesConfirmLogout.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(3));
            Delay.Duration(10000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Firefox.Steward.lb_ConfirmLogin' at Center.", repo.Manual1809_Firefox.Steward.lb_ConfirmLoginInfo, new RecordItemIndex(4));
            repo.Manual1809_Firefox.Steward.lb_ConfirmLogin.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
