///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Manual1809_ZEBA_BD1.Requestor.CommonAction
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FilterCR recording.
    /// </summary>
    [TestModule("27bb841a-b8ce-40cf-b422-5ccb5fdbe795", ModuleType.Recording, 1)]
    public partial class FilterCR : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Manual1809_ZEBA_BD1.Manual1809_ZEBA_BD1Repository repository.
        /// </summary>
        public static global::Manual1809_ZEBA_BD1.Manual1809_ZEBA_BD1Repository repo = global::Manual1809_ZEBA_BD1.Manual1809_ZEBA_BD1Repository.Instance;

        static FilterCR instance = new FilterCR();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FilterCR()
        {
            GetCRnumber = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FilterCR Instance
        {
            get { return instance; }
        }

#region Variables

        string _GetCRnumber;

        /// <summary>
        /// Gets or sets the value of variable GetCRnumber.
        /// </summary>
        [TestVariable("33c739e4-d33f-4442-a4d4-786884afa567")]
        public string GetCRnumber
        {
            get { return _GetCRnumber; }
            set { _GetCRnumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.FilterCR.txt_SearchCR' at Center.", repo.Manual1809_Chrome.FilterCR.txt_SearchCRInfo, new RecordItemIndex(0));
            repo.Manual1809_Chrome.FilterCR.txt_SearchCR.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'CR0000005970' with focus on 'Manual1809_Chrome.FilterCR.txt_SearchCR'.", repo.Manual1809_Chrome.FilterCR.txt_SearchCRInfo, new RecordItemIndex(1));
            repo.Manual1809_Chrome.FilterCR.txt_SearchCR.PressKeys("CR0000005970");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Manual1809_Chrome.FilterCR.btn_GoAction' at Center.", repo.Manual1809_Chrome.FilterCR.btn_GoActionInfo, new RecordItemIndex(2));
            repo.Manual1809_Chrome.FilterCR.btn_GoAction.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(3));
            Delay.Duration(4000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='APPROVED') on item 'Manual1809_Chrome.FilterCR.lb_APPROVED'.", repo.Manual1809_Chrome.FilterCR.lb_APPROVEDInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.Manual1809_Chrome.FilterCR.lb_APPROVEDInfo, "InnerText", "APPROVED");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='ACTIVATED') on item 'Manual1809_Chrome.FilterCR.lb_Activation_Status'.", repo.Manual1809_Chrome.FilterCR.lb_Activation_StatusInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.Manual1809_Chrome.FilterCR.lb_Activation_StatusInfo, "InnerText", "ACTIVATED");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
