///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Manual1809
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ChooseTemplate recording.
    /// </summary>
    [TestModule("13f28758-d128-423e-b3b1-d2d738c972ca", ModuleType.Recording, 1)]
    public partial class ChooseTemplate : ITestModule
    {
        /// <summary>
        /// Holds an instance of the D4H_BPRepository repository.
        /// </summary>
        public static D4H_BPRepository repo = D4H_BPRepository.Instance;

        static ChooseTemplate instance = new ChooseTemplate();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ChooseTemplate()
        {
            vaOjType = "ZB00_CU_GD1";
            domainname = "dole-dev-simplemdg-web.cfapps.ap11.hana.ondemand.com";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ChooseTemplate Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable vaOjType.
        /// </summary>
        [TestVariable("ef9bbd58-95fc-4fab-ad03-2aa20723a5fe")]
        public string vaOjType
        {
            get { return repo.vaOjType; }
            set { repo.vaOjType = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable domainname.
        /// </summary>
        [TestVariable("b336a5ea-bdfe-45f2-8010-c12900dd620b")]
        public string domainname
        {
            get { return repo.domainname; }
            set { repo.domainname = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Btn_ChooseTemplate' at Center.", repo.ApplicationUnderTest.Btn_ChooseTemplateInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Btn_ChooseTemplate.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_SelectSearch' at Center.", repo.ApplicationUnderTest.txt_SelectSearchInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.txt_SelectSearch.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ZVD01_ZB00' with focus on 'ApplicationUnderTest.txt_SelectSearch'.", repo.ApplicationUnderTest.txt_SelectSearchInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.txt_SelectSearch.PressKeys("ZVD01_ZB00");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Btn_SearchAction' at Center.", repo.ApplicationUnderTest.Btn_SearchActionInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Btn_SearchAction.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.lb_ChooseTemplate' at Center.", repo.ApplicationUnderTest.lb_ChooseTemplateInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.lb_ChooseTemplate.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
