///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Manual1809
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InputHeader recording.
    /// </summary>
    [TestModule("5054604b-2c18-4f77-987c-17cea4c41b7b", ModuleType.Recording, 1)]
    public partial class InputHeader : ITestModule
    {
        /// <summary>
        /// Holds an instance of the D4H_BPRepository repository.
        /// </summary>
        public static D4H_BPRepository repo = D4H_BPRepository.Instance;

        static InputHeader instance = new InputHeader();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InputHeader()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InputHeader Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.InputHeader.txt_RequestDescription' at Center.", repo.ApplicationUnderTest.InputHeader.txt_RequestDescriptionInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.InputHeader.txt_RequestDescription.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1890 Gen Auto for BP' with focus on 'ApplicationUnderTest.InputHeader.txt_RequestDescription'.", repo.ApplicationUnderTest.InputHeader.txt_RequestDescriptionInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.InputHeader.txt_RequestDescription.PressKeys("1890 Gen Auto for BP");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.InputHeader.txt_Priority' at Center.", repo.ApplicationUnderTest.InputHeader.txt_PriorityInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.InputHeader.txt_Priority.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'MEDIUM' with focus on 'ApplicationUnderTest.InputHeader.txt_Priority'.", repo.ApplicationUnderTest.InputHeader.txt_PriorityInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.InputHeader.txt_Priority.PressKeys("MEDIUM");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.InputHeader.txt_Reason' at Center.", repo.ApplicationUnderTest.InputHeader.txt_ReasonInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.InputHeader.txt_Reason.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'New Business Partner' with focus on 'ApplicationUnderTest.InputHeader.txt_Reason'.", repo.ApplicationUnderTest.InputHeader.txt_ReasonInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.InputHeader.txt_Reason.PressKeys("New Business Partner");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.InputHeader.txt_OtherReason' at Center.", repo.ApplicationUnderTest.InputHeader.txt_OtherReasonInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.InputHeader.txt_OtherReason.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'JUST for Testing' with focus on 'ApplicationUnderTest.InputHeader.txt_OtherReason'.", repo.ApplicationUnderTest.InputHeader.txt_OtherReasonInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.InputHeader.txt_OtherReason.PressKeys("JUST for Testing");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
