///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Manual1809
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Manual1809Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("69734461-482b-412b-a4ba-a50106269fdb")]
    public partial class Manual1809Repository : RepoGenBaseFolder
    {
        static Manual1809Repository instance = new Manual1809Repository();

        /// <summary>
        /// Gets the singleton class instance representing the Manual1809Repository element repository.
        /// </summary>
        [RepositoryFolder("69734461-482b-412b-a4ba-a50106269fdb")]
        public static Manual1809Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Manual1809Repository() 
            : base("Manual1809Repository", "/", null, 0, false, "69734461-482b-412b-a4ba-a50106269fdb", ".\\RepositoryImages\\Manual1809Repository69734461.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("69734461-482b-412b-a4ba-a50106269fdb")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Manual1809RepositoryFolders
    {
    }
#pragma warning restore 0436
}
