///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Manual1809
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Submit_Request recording.
    /// </summary>
    [TestModule("16c29678-ecf0-42b5-bbf6-f5d33616e4d0", ModuleType.Recording, 1)]
    public partial class Submit_Request : ITestModule
    {
        /// <summary>
        /// Holds an instance of the D4H_BPRepository repository.
        /// </summary>
        public static D4H_BPRepository repo = D4H_BPRepository.Instance;

        static Submit_Request instance = new Submit_Request();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Submit_Request()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Submit_Request Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.Btn_SubmitRequest'", repo.ApplicationUnderTest.Btn_SubmitRequestInfo, new ActionTimeout(5000), new RecordItemIndex(0));
            repo.ApplicationUnderTest.Btn_SubmitRequestInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Btn_SubmitRequest' at Center.", repo.ApplicationUnderTest.Btn_SubmitRequestInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Btn_SubmitRequest.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_SelectOT' at Center.", repo.ApplicationUnderTest.txt_SelectOTInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.txt_SelectOT.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Business Partner' with focus on 'ApplicationUnderTest.txt_SelectOT'.", repo.ApplicationUnderTest.txt_SelectOTInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.txt_SelectOT.PressKeys("Business Partner");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Btn_Next' at Center.", repo.ApplicationUnderTest.Btn_NextInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Btn_Next.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
